/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 HB.gltf --transform
*/


import { useGLTF, PerspectiveCamera } from '@react-three/drei'

/* eslint-disable no-sequences */
import { useEffect,  useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'

import { useSnapshot } from "valtio"
import state from "../state"

export function Case(props) {


  const [hovered, setHovered] = useState(null);
  const group = useRef();
  const snap = useSnapshot(state);
  const { nodes, materials } = useGLTF('/HB-transformed.glb')

  // Animate model
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    group.current.rotation.z = -0.2 - (1 + Math.sin(t / 1.5)) / 20;
    group.current.rotation.x = Math.cos(t / 4) / 8;
    group.current.rotation.y = Math.sin(t / 4) / 8;
    group.current.position.y = (1 + Math.sin(t / 1.5)) / 10;
  });

  useEffect(() => {
    const cursor = `<svg width="64" height="64" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0)"><path fill="rgba(255, 255, 255, 0.5)" d="M29.5 54C43.031 54 54 43.031 54 29.5S43.031 5 29.5 5 5 15.969 5 29.5 15.969 54 29.5 54z" stroke="#000"/><g filter="url(#filter0_d)"><path d="M29.5 47C39.165 47 47 39.165 47 29.5S39.165 12 29.5 12 12 19.835 12 29.5 19.835 47 29.5 47z" fill="${snap.items[hovered]}"/></g><path d="M2 2l11 2.947L4.947 13 2 2z" fill="#000"/><text fill="#000" style="white-space:pre" font-family="Inter var, sans-serif" font-size="10" letter-spacing="-.01em"><tspan x="35" y="63">${hovered}</tspan></text></g><defs><clipPath id="clip0"><path fill="#fff" d="M0 0h64v64H0z"/></clipPath><filter id="filter0_d" x="6" y="8" width="47" height="47" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="2"/><feGaussianBlur stdDeviation="3"/><feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.15 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow"/><feBlend in="SourceGraphic" in2="effect1_dropShadow" result="shape"/></filter></defs></svg>`;
    const auto = `<svg width="64" height="64" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="rgba(255, 255, 255, 0.5)" d="M29.5 54C43.031 54 54 43.031 54 29.5S43.031 5 29.5 5 5 15.969 5 29.5 15.969 54 29.5 54z" stroke="#000"/><path d="M2 2l11 2.947L4.947 13 2 2z" fill="#000"/></svg>`;
    document.body.style.cursor = `url('data:image/svg+xml;base64,${btoa(
      hovered ? cursor : auto
    )}'), auto`;
  }, [hovered, snap.items]);

  return (
    <group {...props} dispose={null}    
    ref={group}    
    onPointerOver={(e) => (
      e.stopPropagation(), setHovered(e.object.material.name)
    )}
    onPointerOut={(e) => e.intersections.length === 0 && setHovered(null)}
    onPointerMissed={() => (state.current = null)}
    onPointerDown={(e) => (
      e.stopPropagation(), (state.current = e.object.material.name)
    )}
  
    >
      <group scale={0.1}>
        <group position={[0, 0.17, 0]} >
          <group position={[0.43, 0.8, 0.19]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
            <mesh  geometry={nodes.M3_standoff_9.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[2.27, 0, -1.24]} rotation={[Math.PI, -1.31, -Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_10.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0, 0, -1.24]} rotation={[-Math.PI, -1.25, -Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_11.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.23, 0, -2.82]} rotation={[0, -1.45, 0]} />
            <mesh  geometry={nodes['RG-PANEL-SUPPORT-CA-Y101_1'].geometry} material={materials['Mold-Tech-11020 #3']} position={[2.58, -0.8, -3.37]} rotation={[Math.PI, 0, 0]} />
            <mesh  geometry={nodes['1345348492'].geometry} material={materials['Paint Matte Black #4']} />
            <mesh  geometry={nodes['MB-RUBBER-CA-P101_2'].geometry} material={materials['Rubber #1 #2']} position={[2.34, -0.01, -1.88]} rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_12.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.55, 0, -2.82]} rotation={[-Math.PI, -1.53, Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_13.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[2.27, 0, -2.82]} rotation={[-Math.PI, -1.41, -Math.PI]} />
            <mesh  geometry={nodes['MB-RUBBER-CA-P101_3'].geometry} material={materials['Rubber #1 #2']} position={[2.34, -0.01, -0.63]} rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_14.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.55, 0, -1.24]} rotation={[-Math.PI, -1.26, -Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_15.geometry} material={materials['Anodized Aluminum Rough Black #2']} rotation={[-Math.PI, -1.29, -Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_16.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.55, 0, 0]} rotation={[-Math.PI, -1.38, Math.PI]} />
            <mesh  geometry={nodes.M3_standoff_17.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[2.27, 0, 0]} rotation={[Math.PI, -1.52, -Math.PI]} />
            <mesh  geometry={nodes.flat_head_screw_am_4.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[2.58, -0.82, -1.63]} rotation={[-Math.PI, -0.99, -Math.PI / 2]} />
            <mesh  geometry={nodes.flat_head_screw_am_5.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[2.58, -0.82, -3.32]} rotation={[0, 0, Math.PI / 2]} />
          </group>
          <group position={[0, 0, -0.01]}>
            <group position={[0.63, 2.82, 0.01]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh  geometry={nodes['thumb_screw_6-32_7'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.58, 0.14, -0.05]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh  geometry={nodes['HDD-TRAY-CA-Y101_2'].geometry} material={materials['Paint Matte Black #4']} />
              <mesh  geometry={nodes['thumb_screw_6-32_8'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.58, 0.14, -0.05]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
            <group position={[0.95, 2.82, 0.01]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh  geometry={nodes['thumb_screw_6-32_9'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.58, 0.14, -0.05]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh  geometry={nodes['HDD-TRAY-CA-Y101_3'].geometry} material={materials['Paint Matte Black #4']} />
              <mesh  geometry={nodes['thumb_screw_6-32_10'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.58, 0.14, -0.05]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
            <group position={[-0.7, 3.01, 0.09]}>
              <group position={[0, 0, 0.02]}>
                <mesh  geometry={nodes['ZB-FAN-1110_7'].geometry} material={materials['Translucent Candle Wax #2 #2']} />
                <mesh  geometry={nodes['ZB-FAN-1110_8'].geometry} material={materials['Translucent Candle Wax #2 #2']} />
              </group>
              <mesh  geometry={nodes['BODY-FAN-CL-Y101_5'].geometry} material={materials['Mold-Tech-11020 #3']} rotation={[Math.PI / 2, 0, 0]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_40'].geometry} material={materials['Rubber #2']} position={[-0.52, -0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_41'].geometry} material={materials['Rubber #2']} position={[-0.52, 0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_42'].geometry} material={materials['Rubber #2']} position={[0.52, 0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_43'].geometry} material={materials['Rubber #2']} position={[0.52, 0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_44'].geometry} material={materials['Rubber #2']} position={[0.52, -0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_45'].geometry} material={materials['Rubber #2']} position={[-0.52, -0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_46'].geometry} material={materials['Rubber #2']} position={[-0.52, 0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
              <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_47'].geometry} material={materials['Rubber #2']} position={[0.52, -0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            </group>
            <group position={[-0.64, 0.63, 0.1]}>
              <group position={[0.28, 1.19, 0]}>
                <mesh  geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_1'].geometry} material={materials['Paint Matte Grey #2']} />
                <mesh  geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_0'].geometry} material={materials['Mold-Tech-11020 #1 #3']} />
                <mesh  geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_1_1'].geometry} material={materials['Mold-Tech-11020 #1 #3']} />
              </group>
              <group position={[0.02, -0.03, 0.43]}>
                <mesh  geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101_1'].geometry} material={materials['Rubber #2']} />
                <mesh  geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101_2'].geometry} material={materials['Rubber #2']} />
              </group>
              <mesh  geometry={nodes['BKT-PCIE-PLASTIC-BASE-CA-Y101_1'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.28, 1.19, 0]} />
              <mesh  geometry={nodes['BKT-PCIE-CA-Y101_13'].geometry} material={materials['Paint Matte Black #4']} position={[0.96, 1.16, -0.01]} rotation={[0, 0, Math.PI / 2]} />
            </group>
            <mesh  geometry={nodes['BKT-PCIE-CA-Y101_6'].geometry} material={materials['Paint Matte Black #4']} position={[0.32, 0.97, 0.09]} rotation={[0, 0, Math.PI / 2]} />
            <mesh  geometry={nodes['BKT-PCIE-CA-Y101_7'].geometry} material={materials['Paint Matte Black #4']} position={[0.32, 1.58, 0.09]} rotation={[0, 0, Math.PI / 2]} />
            <mesh  geometry={nodes['BKT-PCIE-CA-Y101_8'].geometry} material={materials['Paint Matte Black #4']} position={[0.32, 1.38, 0.09]} rotation={[0, 0, Math.PI / 2]} />
            <mesh  geometry={nodes['BKT-PCIE-CA-Y101_9'].geometry} material={materials['Paint Matte Black #4']} position={[0.32, 1.18, 0.09]} rotation={[0, 0, Math.PI / 2]} />
            <mesh  geometry={nodes['BKT-PCIE-CA-Y101_10'].geometry} material={materials['Paint Matte Black #4']} position={[0.32, 0.77, 0.09]} rotation={[0, 0, Math.PI / 2]} />
            <mesh  geometry={nodes['BKT-PCIE-CA-Y101_11'].geometry} material={materials['Paint Matte Black #4']} position={[0.32, 1.99, 0.09]} rotation={[0, 0, Math.PI / 2]} />
            <mesh  geometry={nodes['1344998210'].geometry} material={materials['Paint Matte Black #4']} position={[0, 0, 0.01]} />
            <mesh  geometry={nodes['BKT-HDD-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} position={[0.63, 2.82, 0.04]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_am_15.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.54, 0.61, 1.48]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_head_tapping_screw_am_4.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.22, 3.54, 0.05]} rotation={[Math.PI / 2, -1.11, Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_ai_29.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.4, 0.89, 0]} />
            <mesh  geometry={nodes['BKT-PCIE-V2-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} position={[-1.11, 0.65, 0.09]} />
            <mesh  geometry={nodes.pan_cross_head_ai_30.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.4, 1.3, 0]} />
            <mesh  geometry={nodes.pan_cross_head_ai_31.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.4, 1.5, 0]} />
            <mesh  geometry={nodes.pan_head_tapping_screw_am_5.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.17, 3.54, 0.05]} rotation={[Math.PI / 2, -0.95, Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_ai_32.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.4, 1.7, 0.02]} />
            <mesh  geometry={nodes.pan_cross_head_ai_33.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.4, 1.91, 0.02]} />
            <mesh  geometry={nodes.pan_cross_head_ai_34.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.01, 1.7, 0.03]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_ai_35.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.81, 1.7, 0.03]} rotation={[0, 0.19, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_head_tapping_screw_am_6.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.22, 2.49, 0.05]} rotation={[Math.PI / 2, -0.82, Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_am_16.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.52, 0.61, 1.06]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_ai_36.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.4, 0.69, 0]} />
            <mesh  geometry={nodes.pan_cross_head_am_17.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.52, 0.61, 1.39]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_ai_37.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.6, 1.7, 0.03]} rotation={[0, 0.41, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_ai_38.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.4, 1.09, 0]} />
            <mesh  geometry={nodes.pan_head_tapping_screw_am_7.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.17, 2.49, 0.05]} rotation={[Math.PI / 2, -0.73, Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_am_18.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.65, 0.61, 0.46]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes.pan_cross_head_am_19.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.52, 0.61, 0.56]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[0, 3.92, 4.33]} rotation={[0, 1.57, 0]}>
            <mesh  geometry={nodes['1344715243_1'].geometry} material={materials['Paint Matte Black #1 #3']} position={[-0.01, -0.05, -0.4]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes['1344715244'].geometry} material={materials['Paint Matte Black #4']} />
          </group>
          <mesh  geometry={nodes['1344715242'].geometry} material={materials['Glass Basic White #2']} material-color={snap.items['Glass Basic White #2']}  visible={!snap.items.removeCase} />
          <mesh  geometry={nodes['1344715243'].geometry} material={materials['Paint Matte Black #1 #3']} />
          <mesh  geometry={nodes['1344715245'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[-0.4, 3.86, 4.3]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh  geometry={nodes['1344715245_1'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.37, 0.86, 4.28]} rotation={[-1.18, 0, Math.PI]} />
          <mesh  geometry={nodes['1344715246'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.37, 2.21, 4.28]} rotation={[-1.18, 0, Math.PI]} />
          <mesh  geometry={nodes['1344715246_1'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.37, 3.56, 4.28]} rotation={[-1.18, 0, Math.PI]} />
          <mesh  geometry={nodes['1344732233'].geometry} material={materials['Paint Matte Black #1 #3']} />
          <mesh  geometry={nodes['1344732233_1'].geometry} material={materials['Glass Basic White #2']} visible={!snap.items.removeCase} />
          <mesh  geometry={nodes['1346367342'].geometry} material={materials['Paint Matte Black #4']} />
          <mesh  geometry={nodes['1344732234'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.2, 3.79, 3.68]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes['1344732234_1'].geometry} material={materials['Mold-Tech-11020 #3']} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh  geometry={nodes['1344732235'].geometry} material={materials['Rubber #2']} />
          <mesh  geometry={nodes['1344732236'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.7, 3.79, 4.17]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes['1344732237'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.38, 0.48, 3.61]} rotation={[0, 0.17, -Math.PI / 2]} />
          <mesh  geometry={nodes['1344732237_1'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.64, 0.48, 4.36]} rotation={[0, 0.36, -Math.PI / 2]} />
          <group position={[-1.36, 3.92, 0.13]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh  geometry={nodes['1344755256'].geometry} material={materials['Paint Matte Black #1 #3']} position={[-0.01, -2.8, -0.05]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh  geometry={nodes['1344755257'].geometry} material={materials['Paint Matte Black #4']} />
            <mesh  geometry={nodes['1344755257_1'].geometry} material={materials['Paint Matte Black #1 #3']} position={[-0.01, -1, -0.05]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <mesh  geometry={nodes['1344755258'].geometry} material={materials['Paint Matte Black #1 #3']} />
          <mesh  geometry={nodes['1344755258_1'].geometry} material={materials['Glass Basic White #2']} visible={!snap.items.removeCase} />
          <mesh  geometry={nodes['1344755258_2'].geometry} material={materials['Paint Matte Black #4']} />
          <mesh  geometry={nodes['1344755258_3'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[-1.32, 3.86, 2.92]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh  geometry={nodes['1344755259'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[-1.32, 3.86, 1.13]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh  geometry={nodes['1344755259_1'].geometry} material={materials['Mold-Tech-11020 #3']} position={[-1.25, 3.7, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh  geometry={nodes['1344755259_2'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.36, 3.7, -0.03]} rotation={[Math.PI / 2, 0.39, -Math.PI]} />
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.97, -3.94, 0.25]} rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI]}>
              <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh  geometry={nodes.SWITH_LED_1_AF0_1.geometry} material={materials['Anodized Aluminum Rough Black #2']} />
                <mesh  geometry={nodes.SWITH_LED_1_AF0_2.geometry} material={materials['Anodized Aluminum Rough Black #2']} />
                <mesh  geometry={nodes.SWITH_LED_1_AF0_3.geometry} material={materials['Anodized Aluminum Rough Black #2']} />
                <mesh  geometry={nodes.SWITH_LED_1_AF0_4.geometry} material={materials['Anodized Aluminum Rough Black #2']} />
                <mesh  geometry={nodes.SWITH_LED_1_AF0_5.geometry} material={materials['Anodized Aluminum Rough Black #2']} />
                <mesh  geometry={nodes.SWITH_LED_1_AF0_6.geometry} material={materials['Anodized Aluminum Rough Black #2']} />
                <mesh  geometry={nodes.SWITH_LED_1_AF0_7.geometry} material={materials['Anodized Aluminum Rough Black #2']} />
              </group>
              <group position={[0, -0.11, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh  geometry={nodes['WAFER-HOUSING-P20-V-6P_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
                <mesh  geometry={nodes['WAFER-HOUSING-P20-V-6P_2'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-P20-V-6P_3'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-P20-V-6P_4'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-P20-V-6P_5'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-P20-V-6P_6'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-P20-V-6P_7'].geometry} material={materials['Steel Rough   #2']} />
              </group>
              <group position={[-0.4, 0, 0.15]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh  geometry={nodes['TYPC-180_AF2_1'].geometry} material={materials['Rubber #1 #2']} />
                <mesh  geometry={nodes['TYPC-180_AF2_2'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['TYPC-180_AF2_3'].geometry} material={materials['Mold-Tech-11020 #3']} />
              </group>
              <group position={[0.33, 0, -0.02]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_1'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_2'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_3'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_4'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_5'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_6'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_7'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_8'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_9'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_10'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['WAFER-HOUSING-2-P20-V-10P_11'].geometry} material={materials['Steel Rough   #2']} />
              </group>
              <group position={[-0.23, 0, 0.01]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_2'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_3'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_4'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_5'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_6'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_7'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_8'].geometry} material={materials['Mold-Tech-11020 #3']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_0'].geometry} material={materials['Mold-Tech-11020 #3']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_1_1'].geometry} material={materials['Brass Rough #2']} />
              </group>
              <group position={[0.23, 0, 0.01]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_9'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_10'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_11'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_12'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_13'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_14'].geometry} material={materials['Steel Rough   #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_15'].geometry} material={materials['Mold-Tech-11020 #3']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_1_2'].geometry} material={materials['Brass Rough #2']} />
                <mesh  geometry={nodes['CON-USB-3-0-NEW_AF2_0_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
              </group>
              <mesh  geometry={nodes['PCB-CA-Y101_AF0_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
              <mesh  geometry={nodes['AUDIO-JACK-PHANTOM410_1'].geometry} material={materials['Mold-Tech-11020 #3']} position={[0.4, 0, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
            </group>
            <group position={[-1.09, -4.06, 0.26]} rotation={[-Math.PI, 0, Math.PI / 4]}>
              <mesh  geometry={nodes['1344822726'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
              <mesh  geometry={nodes['1344822730'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0, -0.02, 0]} />
            </group>
            <mesh  geometry={nodes['USB-SUPPORT-CA-Y101_1'].geometry} material={materials['Anodized Aluminum Rough Black #2']} rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <mesh  geometry={nodes['GLASS-SUPPORT-CA-Y101_4'].geometry} material={materials['Mold-Tech-11020 #3']} position={[-1.35, 0.44, 3.42]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh  geometry={nodes['BOTTOM-PANEL-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} />
          <mesh  geometry={nodes['BOTTOM-PANEL-V3-CA-Y101_1'].geometry} material={materials['Mold-Tech-11020 #3']} position={[0, 0.59, 0]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh  geometry={nodes['GLASS-SUPPORT-CA-Y101_5'].geometry} material={materials['Mold-Tech-11020 #3']} position={[-0.45, 0.44, 4.33]} rotation={[0, -1.57, 0]} />
          <mesh  geometry={nodes['GLASS-SUPPORT-CA-Y101_6'].geometry} material={materials['Mold-Tech-11020 #3']} position={[0.85, 0.44, 4.33]} rotation={[0, -1.57, 0]} />
          <mesh  geometry={nodes.pan_cross_head_am_11.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.64, 0.62, 0.33]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh  geometry={nodes['GLASS-SUPPORT-CA-Y101_7'].geometry} material={materials['Mold-Tech-11020 #3']} position={[-1.35, 0.44, 0.42]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh  geometry={nodes.pan_cross_head_am_12.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.43, 0.62, 1.65]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_am_13.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.64, 0.62, 1.65]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh  geometry={nodes['1344792751'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
          <mesh  geometry={nodes.pan_cross_head_am_14.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.43, 0.62, 0.33]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh  geometry={nodes['1344901592'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
          <mesh  geometry={nodes['TOP-COVER-PLASTIC-CA-Y101_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
          <mesh  geometry={nodes['TOP-COVER-PLASTIC-CA-Y101_2'].geometry} material={materials['RealCloth Plain Weave Mesh Black #2']} />
          <mesh  geometry={nodes['1345064208'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
          <mesh  geometry={nodes['STANDOFF-SO-CA-Y101_2'].geometry} material={materials['Paint Matte Black #1 #3']} position={[1.37, 4.24, 3.81]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes['RG-PANEL-FILTER-CA-Y101_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
          <mesh  geometry={nodes['RG-PANEL-FILTER-CA-Y101_2'].geometry} material={materials['RealCloth Plain Weave Mesh Black #2']} />
          <mesh  geometry={nodes['PLACTIC-HANDLE-PANEL-CA-Y101_2'].geometry} material={materials['Mold-Tech-11020 #3']} position={[1.25, 3.7, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh  geometry={nodes['STANDOFF-SO-CA-Y101_3'].geometry} material={materials['Paint Matte Black #1 #3']} position={[1.37, 4.24, 1]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes['thumb_screw_6-32_2'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.35, 3.7, -0.03]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh  geometry={nodes['RIVET-D3-T20_5'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1, 0.02, 0.14]} />
          <mesh  geometry={nodes['RIVET-D3-T20_6'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.3, 0.47, 0.02]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          <mesh  geometry={nodes['RIVET-D3-T20_7'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.15, 0.02, 0.14]} />
          <mesh  geometry={nodes['RIVET-D3-T20_8'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1, 0.02, 0.14]} />
          <mesh  geometry={nodes['FAN-BRACKET-TOP-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} position={[-0.21, 4.07, 0.1]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh  geometry={nodes['TOP-PANEL-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_10'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[1.36, 4.24, 3.81]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_11'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[1.28, 4.33, 0.5]} rotation={[0, 1.57, 0]} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_12'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[1.28, 4.33, 1.95]} rotation={[0, 1.57, 0]} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_13'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[-1.28, 4.33, 0.5]} rotation={[0, 1.57, 0]} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_14'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[-1.28, 4.33, 1.95]} rotation={[0, 1.57, 0]} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_15'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[1.28, 4.33, 3.4]} rotation={[0, 1.57, 0]} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_16'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[-1.28, 4.33, 3.4]} rotation={[0, 1.57, 0]} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_17'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[1.36, 4.24, 1]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh  geometry={nodes['TOP-RING-COVER-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_18'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[0.95, 4.33, 4.26]} />
          <mesh  geometry={nodes['1344854286'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
          <mesh  geometry={nodes['TOP-RING-SUPPORT-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} />
          <mesh  geometry={nodes['LOCK-STANDOFF-SO-H500_19'].geometry} material={materials['Hard Shiny Plastic Black #2']} position={[-0.29, 4.33, 4.26]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_20.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.28, 4.34, 0.6]} rotation={[0, 1.22, -Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_21.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.28, 4.34, 2.05]} rotation={[-Math.PI, 1.47, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_22.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.28, 4.34, 0.4]} rotation={[0, 1.03, -Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_23.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.28, 4.34, 1.85]} rotation={[0, 1.43, -Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_24.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.39, 4.34, 4.26]} rotation={[-Math.PI, 0.81, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_25.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.36, 4.24, 3.71]} rotation={[1.56, 0, -Math.PI]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_26.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-0.19, 4.34, 4.26]} rotation={[-Math.PI, 0.67, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_27.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.28, 4.34, 0.6]} rotation={[-Math.PI, 1.23, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_28.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.28, 4.34, 2.05]} rotation={[-Math.PI, 0.81, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_29.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.28, 4.34, 3.5]} rotation={[-Math.PI, 1, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_30.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.28, 4.34, 3.3]} rotation={[-Math.PI, 1.23, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_31.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.28, 4.34, 1.85]} rotation={[-Math.PI, 1, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_32.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.28, 4.34, 0.4]} rotation={[-Math.PI, 1.47, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_33.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.28, 4.34, 3.3]} rotation={[-Math.PI, 0.67, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_34.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.36, 4.24, 3.91]} rotation={[1.4, 0, Math.PI]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_35.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.36, 4.24, 1.1]} rotation={[1.69, 0, -Math.PI]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_36.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.05, 4.34, 4.26]} rotation={[-Math.PI, 0.54, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_37.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.85, 4.34, 4.26]} rotation={[-Math.PI, 0.58, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_38.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.28, 4.34, 3.5]} rotation={[-Math.PI, 0.58, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_head_100_screw_ai_39.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[1.36, 4.24, 0.9]} rotation={[1.78, 0, Math.PI]} />
          <group position={[-0.51, 0.4, 1.15]} rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 0.02]}>
              <mesh  geometry={nodes['ZB-FAN-1110_3'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
              <mesh  geometry={nodes['ZB-FAN-1110_4'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
            </group>
            <mesh  geometry={nodes['BODY-FAN-CL-Y101_3'].geometry} material={materials['Mold-Tech-11020 #3']} rotation={[Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_24'].geometry} material={materials['Rubber #2']} position={[-0.52, -0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_25'].geometry} material={materials['Rubber #2']} position={[-0.52, 0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_26'].geometry} material={materials['Rubber #2']} position={[0.52, 0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_27'].geometry} material={materials['Rubber #2']} position={[0.52, 0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_28'].geometry} material={materials['Rubber #2']} position={[0.52, -0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_29'].geometry} material={materials['Rubber #2']} position={[-0.52, -0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_30'].geometry} material={materials['Rubber #2']} position={[-0.52, 0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_31'].geometry} material={materials['Rubber #2']} position={[0.52, -0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          </group>
          <group position={[-0.51, 0.4, 2.36]} rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 0.02]}>
              <mesh  geometry={nodes['ZB-FAN-1110_5'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
              <mesh  geometry={nodes['ZB-FAN-1110_6'].geometry} material={materials['Anodized Aluminum Rough Black #2']} />
            </group>
            <mesh  geometry={nodes['BODY-FAN-CL-Y101_4'].geometry} material={materials['Mold-Tech-11020 #3']} rotation={[Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_32'].geometry} material={materials['Rubber #2']} position={[-0.52, -0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_33'].geometry} material={materials['Rubber #2']} position={[-0.52, 0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_34'].geometry} material={materials['Rubber #2']} position={[0.52, 0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_35'].geometry} material={materials['Rubber #2']} position={[0.52, 0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_36'].geometry} material={materials['Rubber #2']} position={[0.52, -0.52, 0.02]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_37'].geometry} material={materials['Rubber #2']} position={[-0.52, -0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_38'].geometry} material={materials['Rubber #2']} position={[-0.52, 0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
            <mesh  geometry={nodes['RUBBER-FAN-CL-Y101_39'].geometry} material={materials['Rubber #2']} position={[0.52, -0.52, 0.23]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
          </group>
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_8.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.14, 0.63]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_ai_21.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.1, 1.83]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_ai_22.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.1, 2.88]} rotation={[0, 0.29, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_9.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.14, 2.88]} rotation={[0, 0.38, Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_ai_23.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.1, 2.88]} rotation={[0, 0.38, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_10.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.14, 1.83]} rotation={[0, 0.16, Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_ai_24.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.1, 1.83]} rotation={[0, 0.16, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_11.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.14, 1.83]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes['BOTTOM-COVER-CA-Y101_1'].geometry} material={materials['Paint Matte Black #4']} />
          <mesh  geometry={nodes['BOTTOM-PLASTIC-CA-Y101_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
          <mesh  geometry={nodes['BOTTOM-PLASTIC-CA-Y101_2'].geometry} material={materials['Mold-Tech-11020 #3']} />
          <mesh  geometry={nodes['BOTTOM-RUBBER-CA-Y101_1'].geometry} material={materials['Rubber #2']} />
          <mesh  geometry={nodes['BOTTOM-RUBBER-CA-Y101_2'].geometry} material={materials['Rubber #2']} />
          <mesh  geometry={nodes['BOTTOM-RUBBER-CA-Y101_3'].geometry} material={materials['Rubber #2']} />
          <mesh  geometry={nodes['BOTTOM-RUBBER-CA-Y101_4'].geometry} material={materials['Rubber #2']} />
          <mesh  geometry={nodes['BOTTOM-FILTER-CA-Y101_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
          <mesh  geometry={nodes['BOTTOM-FILTER-CA-Y101_2'].geometry} material={materials['RealCloth Plain Weave Mesh Black #2']} />
          <mesh  geometry={nodes['POWER-SUPPORT-CA-Y101_1'].geometry} material={materials['Mold-Tech-11020 #3']} />
          <mesh  geometry={nodes['SCREW-F-UNC6-32-7_1'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0, -0.02, 0.18]} rotation={[0, 0, Math.PI]} />
          <mesh  geometry={nodes.pan_cross_head_ai_25.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.1, 0.63]} rotation={[0, 0.16, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_12.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.14, 2.88]} rotation={[0, 0.29, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_13.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.14, 1.68]} rotation={[0, 0.29, Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_ai_26.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.1, 1.68]} rotation={[0, 0.38, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_14.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.14, 0.63]} rotation={[0, 0.16, Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_ai_27.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[0.01, 0.1, 1.68]} rotation={[0, 0.29, Math.PI / 2]} />
          <mesh  geometry={nodes.pan_cross_head_ai_28.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.1, 0.63]} rotation={[0, 0, Math.PI / 2]} />
          <mesh  geometry={nodes.flat_washer_type_a_selected_narrow_ai_15.geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1.04, 0.14, 1.68]} rotation={[0, 0.38, Math.PI / 2]} />
          <mesh  geometry={nodes['RIVET-D3-T20_9'].geometry} material={materials['Anodized Aluminum Rough Black #2']} position={[-1, 0.47, 0.02]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[-0.75, 0.23, 0.96]} rotation={[0, -Math.PI / 4, 0]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[-0.75, 0.23, 0.96]} rotation={[0, -Math.PI / 4, 0]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={19.46} position={[-2.23, 0.23, 0.21]} rotation={[0, -1.57, 0]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[-0.69, 0.56, -0.35]} rotation={[-2.55, -0.81, -2.69]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[-0.33, 0.26, 0.62]} rotation={[-0.62, -0.76, -0.45]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[0.54, 0.56, 0.92]} rotation={[-0.48, 0.61, 0.29]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[-0.46, 0.42, 0.49]} rotation={[-0.83, -0.68, -0.6]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[-0.23, 0.32, 0.32]} rotation={[-0.38, -0.68, -0.24]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[-0.24, 0.2, 0.33]} rotation={[0.34, -0.69, 0.22]} scale={0.1} />
      <PerspectiveCamera makeDefault={false} far={60000} near={0} fov={39.6} position={[0.01, 0.16, 0.52]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/HB-transformed.glb')
