/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 MB1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function MotherBoard(props) {
  const { nodes, materials } = useGLTF('/mother-board.glb')
  return (
    <group {...props} dispose={null} position={[0.014,0.081,0.13]} rotation={[0, Math.PI/2*-1,0]}>
      <PerspectiveCamera makeDefault={false} far={0.023} near={0.001} fov={39.598} position={[0, 0.131, 0]} />
      <PerspectiveCamera makeDefault={false} far={0.972} near={0.81} fov={39.598} position={[-0.398, 0.138, 0.797]} rotation={[0.02, -0.464, 0.009]} />
      <group position={[0, 0.131, 0]}>
        <group scale={0.025}>
          <group position={[-4.64, -5.15, -0.726]} rotation={[Math.PI / 2, 0, 0]}>
            <group position={[4.303, 0, -0.218]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_1'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['choke-mesh'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -8.193]} />
            <mesh geometry={nodes['capacitor-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} position={[8.891, 0, -8.824]} rotation={[0, 0.833, 0]} />
            <mesh geometry={nodes['choke_small-mesh'].geometry} material={materials['16x:color:192:0:0']} position={[5.087, 0, -6.229]} />
            <group position={[6.42, 0, -0.225]}>
              <mesh geometry={nodes['usb_2_header-mesh'].geometry} material={materials['usb 2 header:color:26:26:26']} />
              <mesh geometry={nodes['usb_2_header-mesh_1'].geometry} material={materials['usb 2 header:color:242:194:46']} />
            </group>
            <group position={[9.488, 0.065, -2.394]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['4_pin_fan-mesh'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_1'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <group position={[7.429, 0, -0.98]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_2'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_3'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <group position={[7.823, 0, -0.98]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_4'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_5'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <group position={[6.031, 0.065, -11.888]}>
              <mesh geometry={nodes['4_pin_fan-mesh_2'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_3'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_1'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.576, 0, -9.584]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['capacitor-mesh_2'].geometry} material={materials['PRT0007:color:255:255:0']} position={[5.639, 0, -10.356]} />
            <group position={[2.004, 0, -0.168]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_1'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <group position={[1.829, 0.247, -3.775]} rotation={[0, 0.574, Math.PI]}>
              <mesh geometry={nodes['CR2032_battery-mesh'].geometry} material={materials['CR2032 battery:color:26:26:26']} />
              <mesh geometry={nodes['CR2032_battery-mesh_1'].geometry} material={materials['CR2032 battery:color:229:234:237']} />
              <mesh geometry={nodes['CR2032_battery-mesh_2'].geometry} material={materials['PRT0007:color:255:255:0']} />
            </group>
            <group position={[1.704, 0, -0.168]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_2'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_3'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_3'].geometry} material={materials['capacitor:color:202:209:238']} position={[4.161, 0, -11.576]} rotation={[0, 0.596, 0]} />
            <mesh geometry={nodes['capacitor-mesh_4'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.576, 0, -8.722]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['ddr4_socket-mesh'].geometry} material={materials['16x:color:192:0:0']} position={[7.675, 0.037, -8.639]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['choke_medium-mesh'].geometry} material={materials['16x:color:192:0:0']} position={[4.269, 0, -6.771]} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes['pan_cross_head_am_B1867M_-_M3_x_05_x_8_Type_I_Cross_Recessed_PHMS_--8N-mesh'].geometry} material={materials['pan cross head_am_B18.6.7M - M3 x 0.5 x 8 Type I Cross Recessed PHMS --8N:color:198:193:188']} position={[6.024, 0.394, -5.616]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['mb_24_pin-mesh'].geometry} material={materials['mb 24 pin:color:26:26:26']} position={[9.411, 0, -8.902]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes['choke-mesh_1'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -8.571]} />
            <mesh geometry={nodes['audio_chip-mesh'].geometry} material={materials['hyte mb pcb:color:202:209:238']} position={[0.539, 0.079, -1.591]} />
            <mesh geometry={nodes['choke_medium-mesh_1'].geometry} material={materials['16x:color:192:0:0']} position={[4.829, 0, -6.762]} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes['pan_cross_head_am_B1867M_-_M3_x_05_x_8_Type_I_Cross_Recessed_PHMS_--8N-mesh_1'].geometry} material={materials['pan cross head_am_B18.6.7M - M3 x 0.5 x 8 Type I Cross Recessed PHMS --8N:color:198:193:188']} position={[1.535, 0.394, -5.616]} rotation={[0, 0, -Math.PI / 2]} />
            <group position={[9.033, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh'].geometry} material={materials['2.54 pitch dual pin_no top:color:211:170:33']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_1'].geometry} material={materials['2.54 pitch dual pin_no top:color:202:209:238']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_2'].geometry} material={materials['2.54 pitch dual pin_no top:color:26:26:26']} />
            </group>
            <mesh geometry={nodes['choke-mesh_2'].geometry} material={materials['choke:color:202:209:238']} position={[4.363, 0, -10.711]} rotation={[0, -Math.PI / 2, 0]} />
            <group position={[7.744, 0, -0.98]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_6'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_7'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_5'].geometry} material={materials['PRT0007:color:255:255:0']} position={[5.131, 0, -6.832]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['capacitor-mesh_6'].geometry} material={materials['PRT0007:color:255:255:0']} position={[5.064, 0, -10.356]} />
            <group position={[4.518, 0.072, -5.616]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['M2_NGFF_62mm_short-mesh'].geometry} material={materials['M2 NGFF 6.2mm_short:color:211:170:33']} />
              <mesh geometry={nodes['M2_NGFF_62mm_short-mesh_1'].geometry} material={materials['M2 NGFF 6.2mm_short:color:76:76:76']} />
            </group>
            <group position={[9.333, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_4'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_5'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['dual_stacked_SATA-mesh'].geometry} material={materials['16x:color:192:0:0']} position={[9.049, -0.01, -3.623]} rotation={[0, Math.PI / 2, 0]} />
            <group position={[3.346, 0.072, -2.638]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['M2_SSD-mesh'].geometry} material={materials['M.2 SSD:color:26:26:26']} />
              <mesh geometry={nodes['M2_SSD-mesh_1'].geometry} material={materials['M.2 SSD:color:76:76:76']} />
            </group>
            <group position={[3.615, 0, -0.166]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_6'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_7'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_7'].geometry} material={materials['PRT0007:color:255:255:0']} position={[8.871, 0, -10.74]} rotation={[0, 0.885, 0]} />
            <group position={[4.382, 0, -0.218]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_8'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_9'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['chip_8pin-mesh'].geometry} material={materials['chip 8pin:color:202:209:238']} position={[9.016, 0, -10.125]} />
            <mesh geometry={nodes['capacitor-mesh_8'].geometry} material={materials['PRT0007:color:255:255:0']} position={[8.884, 0, -7.647]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['capacitor-mesh_9'].geometry} material={materials['PRT0007:color:255:255:0']} position={[8.884, 0, -7.36]} rotation={[0, 0.19, 0]} />
            <group position={[3.379, 0.065, -11.888]}>
              <mesh geometry={nodes['4_pin_fan-mesh_4'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_5'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <group position={[8.289, 0.065, -0.112]} rotation={[-Math.PI, 0, Math.PI]}>
              <mesh geometry={nodes['4_pin_fan-mesh_6'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_7'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_10'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.864, 0, -8.722]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['capacitor-mesh_11'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.864, 0, -9.297]} rotation={[0, 0.19, 0]} />
            <group position={[1.604, 0, -0.168]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_8'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_9'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['choke-mesh_3'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -9.325]} />
            <mesh geometry={nodes['dual_stacked_SATA-mesh_1'].geometry} material={materials['16x:color:192:0:0']} position={[9.049, -0.01, -2.954]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes['choke-mesh_4'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -7.816]} />
            <group position={[8.222, 0, -11.892]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_10'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_11'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['ddr4_socket-mesh_1'].geometry} material={materials['16x:color:192:0:0']} position={[7.3, 0.037, -8.639]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            <group position={[8.733, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_12'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_13'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <group position={[7.666, 0, -0.98]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_10'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_11'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['choke-mesh_5'].geometry} material={materials['choke:color:202:209:238']} position={[3.989, 0, -10.711]} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes['chip_8pin_narrow-mesh'].geometry} material={materials['chip 8pin narrow:color:202:209:238']} position={[8.433, 0, -0.597]} rotation={[0, Math.PI / 2, 0]} />
            <group position={[6.928, 0.065, -11.888]}>
              <mesh geometry={nodes['4_pin_fan-mesh_8'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_9'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <mesh geometry={nodes['audio_capacitor-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} position={[1.052, 0, -0.428]} />
            <group position={[7.319, 0.065, -11.888]}>
              <mesh geometry={nodes['4_pin_fan-mesh_10'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_11'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_12'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.576, 0, -8.435]} rotation={[0, 0.19, 0]} />
            <group position={[9.233, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh_1'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:211:170:33']} />
            </group>
            <group position={[1.22, 0.072, -1.535]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['M2_SSD-mesh_2'].geometry} material={materials['M.2 SSD:color:26:26:26']} />
              <mesh geometry={nodes['M2_SSD-mesh_3'].geometry} material={materials['M.2 SSD:color:76:76:76']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_13'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.576, 0, -7.86]} rotation={[0, 0.19, 0]} />
            <group position={[3.111, 0, -0.356]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh_2'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh_3'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['choke-mesh_6'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -8.948]} />
            <mesh geometry={nodes['choke-mesh_7'].geometry} material={materials['choke:color:202:209:238']} position={[5.485, 0, -10.711]} rotation={[0, -Math.PI / 2, 0]} />
            <group position={[9.133, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_14'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_15'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['chip_8pin-mesh_1'].geometry} material={materials['chip 8pin:color:202:209:238']} position={[9.007, 0, -9.854]} />
            <mesh geometry={nodes['audio_capacitor-mesh_1'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.765, 0, -0.715]} />
            <mesh geometry={nodes['capacitor-mesh_14'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.864, 0, -9.009]} rotation={[0, 0.19, 0]} />
            <group position={[9.533, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_16'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_17'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['m2_standoff-mesh'].geometry} material={materials['m2 standoff:color:202:209:238']} position={[1.535, 0, -5.616]} rotation={[0, 0, -Math.PI]} />
            <group position={[9.433, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh_4'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh_5'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_15'].geometry} material={materials['capacitor:color:202:209:238']} position={[9.285, 0, -4.992]} rotation={[0, 0.379, 0]} />
            <mesh geometry={nodes['capacitor-mesh_16'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.576, 0, -9.009]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['pan_cross_head_am_B1867M_-_M3_x_05_x_8_Type_I_Cross_Recessed_PHMS_--8N-mesh_2'].geometry} material={materials['hyte mb pcb:color:202:209:238']} position={[3.346, 0.394, -2.638]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['ddr4_socket-mesh_2'].geometry} material={materials['16x:color:192:0:0']} position={[8.425, 0.037, -8.639]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['capacitor-mesh_17'].geometry} material={materials['PRT0007:color:255:255:0']} position={[1.741, 0, -2.783]} rotation={[0, 0.379, 0]} />
            <group position={[5.419, 0, -0.224]}>
              <mesh geometry={nodes['usb_2_header-mesh_2'].geometry} material={materials['usb 2 header:color:26:26:26']} />
              <mesh geometry={nodes['usb_2_header-mesh_3'].geometry} material={materials['usb 2 header:color:242:194:46']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_18'].geometry} material={materials['PRT0007:color:255:255:0']} position={[2.064, 0, -4.387]} rotation={[0, 0.19, 0]} />
            <group position={[4.461, 0, -0.218]}>
              <mesh geometry={nodes['20_pitch_dual_pin_no_bottom-mesh'].geometry} material={materials['2.0 pitch dual pin_no bottom:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin_no_bottom-mesh_1'].geometry} material={materials['2.0 pitch dual pin_no bottom:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['audio_capacitor-mesh_2'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.765, 0, -1.003]} />
            <mesh geometry={nodes['cpu_8_pin_8-mesh'].geometry} material={materials['cpu 8 pin_8:color:26:26:26']} position={[1.57, 0, -11.811]} />
            <mesh geometry={nodes['capacitor-mesh_19'].geometry} material={materials['PRT0007:color:255:255:0']} position={[2.028, 0, -2.783]} rotation={[0, 0.379, 0]} />
            <mesh geometry={nodes['choke-mesh_8'].geometry} material={materials['choke:color:202:209:238']} position={[3.241, 0, -10.711]} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes['choke-mesh_9'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -10.079]} />
            <group position={[4.203, 0.072, -1.535]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['M2_NGFF_62mm_short-mesh_2'].geometry} material={materials['M2 NGFF 6.2mm_short:color:211:170:33']} />
              <mesh geometry={nodes['M2_NGFF_62mm_short-mesh_3'].geometry} material={materials['M2 NGFF 6.2mm_short:color:76:76:76']} />
            </group>
            <group position={[8.933, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_18'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_19'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['audio_capacitor-mesh_3'].geometry} material={materials['PRT0007:color:255:255:0']} position={[1.052, 0, -0.141]} />
            <group position={[2.649, 0.065, -0.112]} rotation={[Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes['4_pin_fan-mesh_12'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_13'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <group position={[5.35, 0, -6.235]}>
              <group position={[-5.338, 0, -2.975]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes['quad_usb_shield-mesh'].geometry} material={materials['quad usb shield:color:165:158:150']} position={[0, 0.642, 0]} />
                <group position={[-0.258, 0, 0.003]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                  <mesh geometry={nodes['usb3x4-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} />
                  <mesh geometry={nodes['usb3x4-mesh_1'].geometry} material={materials['usb3x4:color:2:61:210']} />
                </group>
              </group>
              <group position={[-5.322, 0.138, -4.746]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes['displayport-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} />
                <mesh geometry={nodes['displayport-mesh_1'].geometry} material={materials['displayport:color:165:158:150']} />
              </group>
              <group position={[-5.338, 0, -3.821]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes['quad_usb_shield-mesh_1'].geometry} material={materials['quad usb shield:color:165:158:150']} position={[0, 0.642, 0]} />
                <group position={[-0.258, 0, 0.003]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                  <mesh geometry={nodes['usb3x4-mesh_2'].geometry} material={materials['PRT0007:color:255:255:0']} />
                  <mesh geometry={nodes['usb3x4-mesh_3'].geometry} material={materials['usb3x4:color:2:61:210']} />
                </group>
              </group>
              <group position={[-5.35, 0, -0.498]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes['Audio_module_shield-mesh'].geometry} material={materials['Audio module shield:color:165:158:150']} position={[0, 0.689, 0]} />
                <group position={[-0.258, 0.698, 0.098]}>
                  <mesh geometry={nodes['35mm_dummy-mesh'].geometry} material={materials['3.5mm dummy:color:229:234:237']} />
                  <mesh geometry={nodes['35mm_dummy-mesh_1'].geometry} material={materials['3.5mm dummy:color:255:239:35']} />
                </group>
                <group position={[0.224, 0.266, 0.098]}>
                  <mesh geometry={nodes['35mm_dummy-mesh_2'].geometry} material={materials['3.5mm dummy:color:229:234:237']} />
                  <mesh geometry={nodes['35mm_dummy-mesh_3'].geometry} material={materials['3.5mm dummy:color:255:239:35']} />
                </group>
                <group position={[-0.258, 0.266, 0.098]}>
                  <mesh geometry={nodes['spdif_housing-mesh'].geometry} material={materials['spdif housing:color:76:76:76']} />
                  <mesh geometry={nodes['spdif_housing-mesh_1'].geometry} material={materials['spdif housing:color:127:127:127']} />
                </group>
                <group position={[0.224, 0.698, 0.098]}>
                  <mesh geometry={nodes['35mm_dummy-mesh_4'].geometry} material={materials['3.5mm dummy:color:229:234:237']} />
                  <mesh geometry={nodes['35mm_dummy-mesh_5'].geometry} material={materials['3.5mm dummy:color:255:239:35']} />
                </group>
                <group position={[0.224, 1.131, 0.098]}>
                  <mesh geometry={nodes['35mm_dummy-mesh_6'].geometry} material={materials['3.5mm dummy:color:229:234:237']} />
                  <mesh geometry={nodes['35mm_dummy-mesh_7'].geometry} material={materials['3.5mm dummy:color:255:239:35']} />
                </group>
                <group position={[-0.258, 1.131, 0.098]}>
                  <mesh geometry={nodes['35mm_dummy-mesh_8'].geometry} material={materials['3.5mm dummy:color:229:234:237']} />
                  <mesh geometry={nodes['35mm_dummy-mesh_9'].geometry} material={materials['3.5mm dummy:color:255:239:35']} />
                </group>
              </group>
              <group position={[-5.35, 0, -1.345]} rotation={[0, -Math.PI / 2, 0]}>
                <group position={[0.055, 0.724, -0.039]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh'].geometry} material={materials['SMA Jack Bulkhead small nut:color:211:170:33']} />
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_1'].geometry} material={materials['SMA Jack Bulkhead small nut:color:255:255:255']} />
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_2'].geometry} material={materials['SMA Jack Bulkhead small nut:color:255:206:127']} />
                </group>
                <group position={[0.055, 0.35, -0.039]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_3'].geometry} material={materials['SMA Jack Bulkhead small nut:color:211:170:33']} />
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_4'].geometry} material={materials['SMA Jack Bulkhead small nut:color:255:255:255']} />
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_5'].geometry} material={materials['SMA Jack Bulkhead small nut:color:255:206:127']} />
                </group>
                <group position={[0.055, 1.097, -0.039]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_6'].geometry} material={materials['SMA Jack Bulkhead small nut:color:211:170:33']} />
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_7'].geometry} material={materials['SMA Jack Bulkhead small nut:color:255:255:255']} />
                  <mesh geometry={nodes['SMA_Jack_Bulkhead_small_nut-mesh_8'].geometry} material={materials['SMA Jack Bulkhead small nut:color:255:206:127']} />
                </group>
                <mesh geometry={nodes['wifi_shield-mesh'].geometry} material={materials['wifi shield:color:165:158:150']} />
              </group>
              <group position={[-5.326, 0.633, -4.746]} rotation={[0, -Math.PI / 2, 0]}>
                <mesh geometry={nodes['hdmi-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} />
                <mesh geometry={nodes['hdmi-mesh_1'].geometry} material={materials['hdmi:color:165:158:150']} />
              </group>
              <group position={[-5.338, 0, -2.043]} rotation={[0, -Math.PI / 2, 0]}>
                <group position={[-0.258, -0.004, 0.003]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                  <mesh geometry={nodes['usb3x2-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} />
                  <mesh geometry={nodes['usb3x2-mesh_1'].geometry} material={materials['usb3x2:color:2:61:210']} />
                </group>
                <mesh geometry={nodes['RJ45_dual_usb_shield-mesh'].geometry} material={materials['RJ45 dual usb shield:color:165:158:150']} position={[0, 0.607, 0]} />
                <group position={[0, 0.909, -0.315]}>
                  <mesh geometry={nodes['RJ45-mesh'].geometry} material={materials['RJ45:color:26:26:26']} />
                  <mesh geometry={nodes['RJ45-mesh_1'].geometry} material={materials['RJ45:color:165:158:150']} />
                  <mesh geometry={nodes['RJ45-mesh_2'].geometry} material={materials['RJ45:color:255:239:35']} />
                  <mesh geometry={nodes['RJ45-mesh_3'].geometry} material={materials['RJ45:color:73:169:84']} />
                </group>
              </group>
            </group>
            <group position={[4.146, 0, -0.218]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_12'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_13'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <group position={[4.225, 0, -0.218]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_14'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_15'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_20'].geometry} material={materials['capacitor:color:202:209:238']} position={[3.373, 0, -11.576]} rotation={[0, 0.596, 0]} />
            <group position={[4.259, 0, -0.448]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh_6'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_bottom-mesh_7'].geometry} material={materials['2.54 pitch dual pin_no bottom:color:211:170:33']} />
            </group>
            <group position={[3.311, 0, -0.356]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_20'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_21'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['16x-mesh'].geometry} material={materials['16x:color:192:0:0']} position={[1.48, 0, -0.804]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes['choke_small-mesh_1'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.772, 0, -3.056]} />
            <mesh geometry={nodes['pan_cross_head_am_B1867M_-_M3_x_05_x_8_Type_I_Cross_Recessed_PHMS_--8N-mesh_3'].geometry} material={materials['hyte mb pcb:color:202:209:238']} position={[1.22, 0.315, -1.535]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['choke-mesh_10'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -7.439]} />
            <mesh geometry={nodes['choke-mesh_11'].geometry} material={materials['choke:color:202:209:238']} position={[5.111, 0, -10.711]} rotation={[0, -Math.PI / 2, 0]} />
            <group position={[6.329, 0.072, -2.638]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['M2_NGFF_62mm_short-mesh_4'].geometry} material={materials['M2 NGFF 6.2mm_short:color:211:170:33']} />
              <mesh geometry={nodes['M2_NGFF_62mm_short-mesh_5'].geometry} material={materials['M2 NGFF 6.2mm_short:color:76:76:76']} />
            </group>
            <mesh geometry={nodes['choke-mesh_12'].geometry} material={materials['choke:color:202:209:238']} position={[4.737, 0, -10.711]} rotation={[0, -Math.PI / 2, 0]} />
            <group position={[8.833, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_22'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_23'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_21'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.576, 0, -8.147]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['capacitor-mesh_22'].geometry} material={materials['PRT0007:color:255:255:0']} position={[8.884, 0, -7.935]} rotation={[0, 0.19, 0]} />
            <group position={[3.815, 0, -0.166]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_3'].geometry} material={materials['2.54 pitch dual pin_no top:color:211:170:33']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_4'].geometry} material={materials['2.54 pitch dual pin_no top:color:202:209:238']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_5'].geometry} material={materials['2.54 pitch dual pin_no top:color:26:26:26']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_23'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.576, 0, -9.297]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['dual_stacked_SATA-mesh_2'].geometry} material={materials['16x:color:192:0:0']} position={[9.049, -0.01, -4.292]} rotation={[0, Math.PI / 2, 0]} />
            <group position={[6.875, 0, -0.115]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_24'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_25'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_24'].geometry} material={materials['PRT0007:color:255:255:0']} position={[4.202, 0, -10.356]} />
            <mesh geometry={nodes['capacitor-mesh_25'].geometry} material={materials['PRT0007:color:255:255:0']} position={[6.966, 0, -9.064]} rotation={[0, 1.111, 0]} />
            <mesh geometry={nodes['pan_cross_head_am_B1867M_-_M3_x_05_x_8_Type_I_Cross_Recessed_PHMS_--8N-mesh_4'].geometry} material={materials['16x:color:192:0:0']} position={[9.291, 0.315, -1.535]} rotation={[0, 0, -Math.PI / 2]} />
            <group position={[4.159, 0, -0.448]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_26'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_27'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['chip_8pin-mesh_2'].geometry} material={materials['PRT0007:color:255:255:0']} position={[9.354, 0, -10.802]} />
            <group position={[8.633, 0, -0.206]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_28'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_29'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['choke-mesh_13'].geometry} material={materials['choke:color:202:209:238']} position={[3.615, 0, -10.711]} rotation={[0, -Math.PI / 2, 0]} />
            <group position={[7.508, 0, -0.98]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_16'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_17'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_26'].geometry} material={materials['PRT0007:color:255:255:0']} position={[9.448, 0, -10.05]} rotation={[0, 0.407, 0]} />
            <group position={[1.904, 0, -0.168]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_6'].geometry} material={materials['2.54 pitch dual pin_no top:color:211:170:33']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_7'].geometry} material={materials['2.54 pitch dual pin_no top:color:202:209:238']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_8'].geometry} material={materials['2.54 pitch dual pin_no top:color:26:26:26']} />
            </group>
            <group position={[1.829, 0.315, -3.775]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['CR2032_battery_holder-mesh'].geometry} material={materials['CR2032 battery holder:color:170:178:196']} />
              <mesh geometry={nodes['CR2032_battery_holder-mesh_1'].geometry} material={materials['CR2032 battery holder:color:76:76:76']} />
            </group>
            <group position={[8.98, 0, -11.892]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_9'].geometry} material={materials['2.54 pitch dual pin_no top:color:211:170:33']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_10'].geometry} material={materials['2.54 pitch dual pin_no top:color:202:209:238']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_11'].geometry} material={materials['2.54 pitch dual pin_no top:color:26:26:26']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_27'].geometry} material={materials['PRT0007:color:255:255:0']} position={[5.351, 0, -10.356]} />
            <mesh geometry={nodes['capacitor-mesh_28'].geometry} material={materials['PRT0007:color:255:255:0']} position={[4.489, 0, -10.356]} />
            <mesh geometry={nodes['capacitor-mesh_29'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.788, 0, -3.335]} rotation={[0, 0.596, 0]} />
            <mesh geometry={nodes['capacitor-mesh_30'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.788, 0, -3.622]} rotation={[0, 0.596, 0]} />
            <group position={[3.534, 0.065, -6.383]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['4_pin_fan-mesh_14'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_15'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <group position={[4.54, 0, -0.218]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_18'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_19'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['chip_8pin_narrow-mesh_1'].geometry} material={materials['chip 8pin narrow:color:202:209:238']} position={[8.144, 0, -0.591]} rotation={[0, Math.PI / 2, 0]} />
            <group position={[6.609, 0.135, -8.687]} rotation={[-Math.PI / 2, 0, 0]}>
              <group position={[-1.297, -0.08, -0.201]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
                <mesh geometry={nodes['xi___-mesh'].geometry} material={materials['xi___:color:255:255:255']} position={[-0.71, 0, 0.64]} />
                <mesh geometry={nodes['xi___-mesh_1'].geometry} material={materials['xi___:color:255:255:255']} position={[0.673, 0, -0.677]} />
                <mesh geometry={nodes['base_board___-mesh'].geometry} material={materials['base board___:color:255:255:255']} />
              </group>
              <group position={[-1.303, -0.073, -0.073]} rotation={[-Math.PI / 2, 0, Math.PI]}>
                <mesh geometry={nodes['top_layer_out___-mesh'].geometry} material={materials['top layer out___:color:164:209:0']} rotation={[0, 0, -Math.PI]} />
                <mesh geometry={nodes['shiled___-mesh'].geometry} material={materials['shiled___:color:229:234:237']} position={[0, 0.043, 0]} />
                <mesh geometry={nodes['copper_layer___-mesh'].geometry} material={materials['copper layer___:color:255:194:11']} position={[0, -0.002, 0]} />
                <mesh geometry={nodes['top_layer_out___-mesh_1'].geometry} material={materials['top layer out___:color:164:209:0']} position={[0, 0.039, 0]} />
                <mesh geometry={nodes['core___-mesh'].geometry} material={materials['core___:color:51:51:51']} position={[0, 0.041, 0]} />
                <mesh geometry={nodes['core_glue___-mesh'].geometry} material={materials['core glue___:color:51:51:51']} position={[0, 0.041, 0]} />
                <mesh geometry={nodes['sheild_words_metal___-mesh'].geometry} material={materials['sheild words metal___:color:255:255:255']} position={[0, 0.161, 0]} />
                <mesh geometry={nodes['top_layer_in___-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0, 0.039, 0]} />
                <mesh geometry={nodes['copper_layer___-mesh_1'].geometry} material={materials['copper layer___:color:255:194:11']} position={[0, 0.039, 0]} />
                <mesh geometry={nodes['bottom_layer_in___-mesh'].geometry} material={materials['bottom layer in___:color:54:76:0']} position={[0, -0.002, 0]} />
                <mesh geometry={nodes['base___-mesh'].geometry} material={materials['base___:color:255:255:255']} />
              </group>
              <group position={[-2.237, 1.193, -0.141]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <mesh geometry={nodes['PRT0007-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} position={[-0.015, -0.004, -0.014]} />
                <mesh geometry={nodes['SRV_TORX_SCREW-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.81, 0.144, -1.566]} />
                <mesh geometry={nodes['SRV_TORX_SCREW-mesh_1'].geometry} material={materials['SRV_TORX_SCREW:color:0:255:255']} position={[0.81, 0.144, -0.149]} />
                <mesh geometry={nodes['SRV_SHOULDER_SCREW-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} position={[-0.436, 0.033, -0.005]} />
                <group position={[0.163, 0.11, 0.031]}>
                  <mesh geometry={nodes['PT44P18-6401-mesh'].geometry} material={materials['PT44P18-6401:color:255:168:0']} />
                  <mesh geometry={nodes['PT44P18-6401-mesh_1'].geometry} material={materials['PRT0007:color:255:255:0']} />
                </group>
                <mesh geometry={nodes['FRAME_-_080304_-_HVM-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} />
                <mesh geometry={nodes['FRAME_INSULATOR_-_080304_-_HVM-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} />
                <mesh geometry={nodes['PRT0008-mesh'].geometry} material={materials['PRT0007:color:255:255:0']} />
              </group>
            </group>
            <mesh geometry={nodes['capacitor-mesh_31'].geometry} material={materials['PRT0007:color:255:255:0']} position={[5.418, 0, -6.832]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['capacitor-mesh_32'].geometry} material={materials['PRT0007:color:255:255:0']} position={[8.891, 0, -9.13]} rotation={[0, 0.644, 0]} />
            <group position={[8.422, 0, -11.892]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_12'].geometry} material={materials['2.54 pitch dual pin_no top:color:211:170:33']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_13'].geometry} material={materials['2.54 pitch dual pin_no top:color:202:209:238']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_14'].geometry} material={materials['2.54 pitch dual pin_no top:color:26:26:26']} />
            </group>
            <group position={[9.462, 0, -6.327]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['usb_3_header-mesh'].geometry} material={materials['16x:color:192:0:0']} />
              <mesh geometry={nodes['usb_3_header-mesh_1'].geometry} material={materials['usb 3 header:color:242:194:46']} />
            </group>
            <mesh geometry={nodes['chip_8pin-mesh_3'].geometry} material={materials['chip 8pin:color:202:209:238']} position={[9.129, 0, -10.447]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes['chip_8pin_skinny-mesh'].geometry} material={materials['chip 8pin skinny:color:202:209:238']} position={[2.733, 0.013, -0.406]} />
            <group position={[4.067, 0, -0.218]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_20'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_21'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_33'].geometry} material={materials['capacitor:color:202:209:238']} position={[4.948, 0, -11.576]} rotation={[0, 0.596, 0]} />
            <mesh geometry={nodes['cpu_8_pin_8-mesh_1'].geometry} material={materials['cpu 8 pin_8:color:26:26:26']} position={[2.37, 0, -11.811]} />
            <mesh geometry={nodes['capacitor-mesh_34'].geometry} material={materials['PRT0007:color:255:255:0']} position={[1.777, 0, -4.387]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['choke-mesh_14'].geometry} material={materials['choke:color:202:209:238']} position={[3.127, 0, -9.702]} />
            <mesh geometry={nodes['audio_capacitor-mesh_4'].geometry} material={materials['PRT0007:color:255:255:0']} position={[1.052, 0, -0.715]} />
            <group position={[3.862, 0.065, -6.383]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['4_pin_fan-mesh_16'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_17'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <group position={[3.049, 0, -0.164]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_30'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_31'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['capacitor-mesh_35'].geometry} material={materials['PRT0007:color:255:255:0']} position={[4.556, 0, -6.832]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['choke_small-mesh_2'].geometry} material={materials['16x:color:192:0:0']} position={[5.556, 0, -6.617]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes['capacitor-mesh_36'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.864, 0, -8.147]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['choke_small-mesh_3'].geometry} material={materials['16x:color:192:0:0']} position={[5.773, 0, -6.621]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes['capacitor-mesh_37'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.788, 0, -2.76]} rotation={[0, 0.596, 0]} />
            <mesh geometry={nodes['16x-mesh_1'].geometry} material={materials['16x:color:192:0:0']} position={[1.48, 0, -4.805]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes['capacitor-mesh_38'].geometry} material={materials['PRT0007:color:255:255:0']} position={[4.776, 0, -10.356]} />
            <mesh geometry={nodes['pan_cross_head_am_B1867M_-_M3_x_05_x_8_Type_I_Cross_Recessed_PHMS_--8N-mesh_5'].geometry} material={materials['16x:color:192:0:0']} position={[6.654, 0.315, -2.638]} rotation={[0, 0, -Math.PI / 2]} />
            <group position={[7.902, 0, -0.98]}>
              <mesh geometry={nodes['20_pitch_dual_pin_no_top-mesh'].geometry} material={materials['2.0 pitch dual pin_no top:color:211:170:33']} />
              <mesh geometry={nodes['20_pitch_dual_pin_no_top-mesh_1'].geometry} material={materials['2.0 pitch dual pin_no top:color:202:209:238']} />
              <mesh geometry={nodes['20_pitch_dual_pin_no_top-mesh_2'].geometry} material={materials['2.0 pitch dual pin_no top:color:26:26:26']} />
            </group>
            <group position={[7.727, 0.065, -0.112]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes['4_pin_fan-mesh_18'].geometry} material={materials['4 pin fan:color:26:26:26']} />
              <mesh geometry={nodes['4_pin_fan-mesh_19'].geometry} material={materials['4 pin fan:color:229:235:237']} />
            </group>
            <group position={[7.587, 0, -0.98]}>
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_22'].geometry} material={materials['2.0 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['20_pitch_dual_pin-mesh_23'].geometry} material={materials['2.0 pitch dual pin:color:211:170:33']} />
            </group>
            <group position={[3.249, 0, -0.164]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_15'].geometry} material={materials['2.54 pitch dual pin_no top:color:211:170:33']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_16'].geometry} material={materials['2.54 pitch dual pin_no top:color:202:209:238']} />
              <mesh geometry={nodes['254_pitch_dual_pin_no_top-mesh_17'].geometry} material={materials['2.54 pitch dual pin_no top:color:26:26:26']} />
            </group>
            <group position={[1.535, 0.072, -5.616]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['M2_SSD-mesh_4'].geometry} material={materials['M.2 SSD:color:26:26:26']} />
              <mesh geometry={nodes['M2_SSD-mesh_5'].geometry} material={materials['M.2 SSD:color:76:76:76']} />
            </group>
            <mesh geometry={nodes['m2_standoff-mesh_1'].geometry} material={materials['m2 standoff:color:202:209:238']} position={[1.22, 0, -1.535]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes['capacitor-mesh_39'].geometry} material={materials['PRT0007:color:255:255:0']} position={[3.864, 0, -9.584]} rotation={[0, 0.19, 0]} />
            <mesh geometry={nodes['1x-mesh'].geometry} material={materials['1x:color:26:26:26']} position={[1.48, 0, -2.405]} rotation={[0, Math.PI / 2, 0]} />
            <group position={[4.359, 0, -0.448]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_32'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_33'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <group position={[8.78, 0, -11.892]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_34'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_35'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['audio_capacitor-mesh_5'].geometry} material={materials['PRT0007:color:255:255:0']} position={[1.052, 0, -1.003]} />
            <mesh geometry={nodes['ddr4_socket-mesh_3'].geometry} material={materials['16x:color:192:0:0']} position={[8.05, 0.037, -8.639]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh geometry={nodes['audio_capacitor-mesh_6'].geometry} material={materials['PRT0007:color:255:255:0']} position={[0.765, 0, -0.428]} />
            <group position={[1.804, 0, -0.168]}>
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_36'].geometry} material={materials['2.54 pitch dual pin:color:26:26:26']} />
              <mesh geometry={nodes['254_pitch_dual_pin-mesh_37'].geometry} material={materials['2.54 pitch dual pin:color:211:170:33']} />
            </group>
            <mesh geometry={nodes['m2_standoff-mesh_2'].geometry} material={materials['m2 standoff:color:202:209:238']} position={[3.346, 0, -2.638]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes['hyte_mb_pcb-mesh'].geometry} material={materials['hyte mb pcb:color:202:209:238']} />
            <mesh geometry={nodes['hyte_mb_pcb-mesh_1'].geometry} material={materials['PRT0007:color:255:255:0']} />
            <mesh geometry={nodes['hyte_mb_pcb-mesh_2'].geometry} material={materials['hyte mb pcb:color:202:209:238 #1']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mother-board.glb')
