/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: Up1x (https://sketchfab.com/alexlh2003)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/power-supply-basic-02db33d66a784c82a6202a3ec6850498
Title: Power Supply - Basic
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Power(props) {
  const { nodes, materials } = useGLTF('/power.glb')
  return (
    <group {...props} dispose={null} scale={[0.0475, 0.046, 0.046]}  position={[0.10, 0.125, 0.05]} rotation={[0, Math.PI,Math.PI/2]} >
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[1.407, 0.117, 1.046]} scale={0.218} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} position={[1.258, 0.247, 0.989]} scale={0.154} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.004']} position={[0.344, 0.312, -0.448]} scale={0.359} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.003']} scale={0.505} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.005']} position={[-0.617, 0, -1.993]} scale={0.248} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} position={[1.746, 0.108, 0.743]} rotation={[Math.PI / 2, 0, 0]} scale={0.032} />
    </group>
  )
}

useGLTF.preload('/power.glb')
