/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 video-card.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera ,useAnimations} from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function VideoCard(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/video-card.glb')
  const { actions } = useAnimations(animations, group)


  const fan1Ref = useRef();
  const fan2Ref = useRef();
  

  useFrame(() => {
    // 旋轉風扇 1
    if (fan1Ref.current) {
      fan1Ref.current.rotation.x -= 0.01;  // 調整旋轉速度
    }
    // // 旋轉風扇 2
    if (fan2Ref.current) {
      fan2Ref.current.rotation.x += 0.01;  // 調整旋轉速度
    }

    // if (fan3Ref.current) {
    //   fan3Ref.current.rotation.y += 0.01;  // 調整旋轉速度
    // }
  });

  return (
    <group ref={group} {...props} dispose={null} scale={[0.1, 0.1, 0.1]}  position={[-0.065, 0.14, 0.12]} rotation={[0, Math.PI,Math.PI]} >
      <group name="Scene">
        <mesh name="Плоскость" geometry={nodes.Плоскость.geometry} material={materials['Материал.001']} position={[0.006, -0.171, -0.159]} rotation={[0, 0, -Math.PI / 2]} scale={[1.657, 2.077, 1.657]} />
        <group name="Куб001" position={[-0.115, -0.176, -0.154]} scale={[0.161, 0.525, 1.027]}>
          <mesh name="Куб001_1" geometry={nodes.Куб001_1.geometry} material={materials['Материал.002']} />
          <mesh name="Куб001_2" geometry={nodes.Куб001_2.geometry} material={materials['Материал.008']} />
          <mesh name="Куб001_3" geometry={nodes.Куб001_3.geometry} material={materials['Материал.101']} />
          <mesh name="Куб001_4" geometry={nodes.Куб001_4.geometry} material={materials['Материал.102']} />
          <mesh name="Куб001_5" geometry={nodes.Куб001_5.geometry} material={materials['Материал.108']} />
          <mesh name="Куб001_6" geometry={nodes.Куб001_6.geometry} material={materials['Материал.107']} />
          <mesh name="Куб001_7" geometry={nodes.Куб001_7.geometry} material={materials['Материал.106']} />
          <mesh name="Куб001_8" geometry={nodes.Куб001_8.geometry} material={materials['Материал.114']} />
          <mesh name="Куб001_9" geometry={nodes.Куб001_9.geometry} material={materials['Материал.113']} />
          <mesh name="Куб001_10" geometry={nodes.Куб001_10.geometry} material={materials['Материал.112']} />
          <mesh name="Куб001_11" geometry={nodes.Куб001_11.geometry} material={materials['Материал.111']} />
          <mesh name="Куб001_12" geometry={nodes.Куб001_12.geometry} material={materials['Материал.110']} />
          <mesh name="Куб001_13" geometry={nodes.Куб001_13.geometry} material={materials['Материал.109']} />
          <mesh name="Куб001_14" geometry={nodes.Куб001_14.geometry} material={materials['Материал.126']} />
          <mesh name="Куб001_15" geometry={nodes.Куб001_15.geometry} material={materials['Материал.125']} />
          <mesh name="Куб001_16" geometry={nodes.Куб001_16.geometry} material={materials['Материал.124']} />
          <mesh name="Куб001_17" geometry={nodes.Куб001_17.geometry} material={materials['Материал.123']} />
          <mesh name="Куб001_18" geometry={nodes.Куб001_18.geometry} material={materials['Материал.122']} />
          <mesh name="Куб001_19" geometry={nodes.Куб001_19.geometry} material={materials['Материал.121']} />
          <mesh name="Куб001_20" geometry={nodes.Куб001_20.geometry} material={materials['Материал.120']} />
          <mesh name="Куб001_21" geometry={nodes.Куб001_21.geometry} material={materials['Материал.119']} />
          <mesh name="Куб001_22" geometry={nodes.Куб001_22.geometry} material={materials['Материал.118']} />
          <mesh name="Куб001_23" geometry={nodes.Куб001_23.geometry} material={materials['Материал.117']} />
          <mesh name="Куб001_24" geometry={nodes.Куб001_24.geometry} material={materials['Материал.116']} />
          <mesh name="Куб001_25" geometry={nodes.Куб001_25.geometry} material={materials['Материал.115']} />
          <mesh name="Куб001_26" geometry={nodes.Куб001_26.geometry} material={materials['Материал.150']} />
          <mesh name="Куб001_27" geometry={nodes.Куб001_27.geometry} material={materials['Материал.149']} />
          <mesh name="Куб001_28" geometry={nodes.Куб001_28.geometry} material={materials['Материал.148']} />
          <mesh name="Куб001_29" geometry={nodes.Куб001_29.geometry} material={materials['Материал.147']} />
          <mesh name="Куб001_30" geometry={nodes.Куб001_30.geometry} material={materials['Материал.146']} />
          <mesh name="Куб001_31" geometry={nodes.Куб001_31.geometry} material={materials['Материал.145']} />
          <mesh name="Куб001_32" geometry={nodes.Куб001_32.geometry} material={materials['Материал.144']} />
          <mesh name="Куб001_33" geometry={nodes.Куб001_33.geometry} material={materials['Материал.143']} />
          <mesh name="Куб001_34" geometry={nodes.Куб001_34.geometry} material={materials['Материал.141']} />
          <mesh name="Куб001_35" geometry={nodes.Куб001_35.geometry} material={materials['Материал.140']} />
          <mesh name="Куб001_36" geometry={nodes.Куб001_36.geometry} material={materials['Материал.139']} />
        </group>
        <mesh name="Куб042" geometry={nodes.Куб042.geometry} material={materials['Материал.142']} position={[-0.077, 0.381, 0.084]} rotation={[Math.PI / 4, 0, 0]} scale={[0.107, 0.55, 0.005]} />
        <mesh name="Куб027" geometry={nodes.Куб027.geometry} material={materials['Материал.127']} position={[-0.077, 0.372, 0.096]} rotation={[Math.PI / 4, 0, 0]} scale={[0.107, 0.55, 0.005]} />
        <group name="Куб076" position={[-0.118, 0.041, -0.422]} rotation={[-Math.PI, 0, 0]} scale={[0.161, 0.525, 1.027]}>
          <mesh name="Куб338" geometry={nodes.Куб338.geometry} material={materials['Материал.189']} />
          <mesh name="Куб338_1" geometry={nodes.Куб338_1.geometry} material={materials['Материал.188']} />
          <mesh name="Куб338_2" geometry={nodes.Куб338_2.geometry} material={materials['Материал.187']} />
          <mesh name="Куб338_3" geometry={nodes.Куб338_3.geometry} material={materials['Материал.186']} />
          <mesh name="Куб338_4" geometry={nodes.Куб338_4.geometry} material={materials['Материал.185']} />
          <mesh name="Куб338_5" geometry={nodes.Куб338_5.geometry} material={materials['Материал.184']} />
          <mesh name="Куб338_6" geometry={nodes.Куб338_6.geometry} material={materials['Материал.183']} />
          <mesh name="Куб338_7" geometry={nodes.Куб338_7.geometry} material={materials['Материал.182']} />
          <mesh name="Куб338_8" geometry={nodes.Куб338_8.geometry} material={materials['Материал.181']} />
          <mesh name="Куб338_9" geometry={nodes.Куб338_9.geometry} material={materials['Материал.180']} />
          <mesh name="Куб338_10" geometry={nodes.Куб338_10.geometry} material={materials['Материал.179']} />
          <mesh name="Куб338_11" geometry={nodes.Куб338_11.geometry} material={materials['Материал.178']} />
          <mesh name="Куб338_12" geometry={nodes.Куб338_12.geometry} material={materials['Материал.177']} />
          <mesh name="Куб338_13" geometry={nodes.Куб338_13.geometry} material={materials['Материал.176']} />
          <mesh name="Куб338_14" geometry={nodes.Куб338_14.geometry} material={materials['Материал.175']} />
          <mesh name="Куб338_15" geometry={nodes.Куб338_15.geometry} material={materials['Материал.174']} />
          <mesh name="Куб338_16" geometry={nodes.Куб338_16.geometry} material={materials['Материал.173']} />
          <mesh name="Куб338_17" geometry={nodes.Куб338_17.geometry} material={materials['Материал.172']} />
          <mesh name="Куб338_18" geometry={nodes.Куб338_18.geometry} material={materials['Материал.171']} />
          <mesh name="Куб338_19" geometry={nodes.Куб338_19.geometry} material={materials['Материал.170']} />
          <mesh name="Куб338_20" geometry={nodes.Куб338_20.geometry} material={materials['Материал.169']} />
          <mesh name="Куб338_21" geometry={nodes.Куб338_21.geometry} material={materials['Материал.168']} />
          <mesh name="Куб338_22" geometry={nodes.Куб338_22.geometry} material={materials['Материал.167']} />
          <mesh name="Куб338_23" geometry={nodes.Куб338_23.geometry} material={materials['Материал.166']} />
          <mesh name="Куб338_24" geometry={nodes.Куб338_24.geometry} material={materials['Материал.165']} />
          <mesh name="Куб338_25" geometry={nodes.Куб338_25.geometry} material={materials['Материал.164']} />
          <mesh name="Куб338_26" geometry={nodes.Куб338_26.geometry} material={materials['Материал.163']} />
          <mesh name="Куб338_27" geometry={nodes.Куб338_27.geometry} material={materials['Материал.162']} />
          <mesh name="Куб338_28" geometry={nodes.Куб338_28.geometry} material={materials['Материал.161']} />
          <mesh name="Куб338_29" geometry={nodes.Куб338_29.geometry} material={materials['Материал.160']} />
          <mesh name="Куб338_30" geometry={nodes.Куб338_30.geometry} material={materials['Материал.159']} />
          <mesh name="Куб338_31" geometry={nodes.Куб338_31.geometry} material={materials['Материал.158']} />
          <mesh name="Куб338_32" geometry={nodes.Куб338_32.geometry} material={materials['Материал.157']} />
          <mesh name="Куб338_33" geometry={nodes.Куб338_33.geometry} material={materials['Материал.156']} />
          <mesh name="Куб338_34" geometry={nodes.Куб338_34.geometry} material={materials['Материал.155']} />
          <mesh name="Куб338_35" geometry={nodes.Куб338_35.geometry} material={materials['Материал.154']} />
          <mesh name="Куб338_36" geometry={nodes.Куб338_36.geometry} material={materials['Материал.153']} />
          <mesh name="Куб338_37" geometry={nodes.Куб338_37.geometry} material={materials['Материал.152']} />
        </group>
        <group name="Куб077" position={[-0.266, -0.159, -0.133]} scale={[0.166, 0.541, 1.058]}>
          <mesh name="Куб099" geometry={nodes.Куб099.geometry} material={materials['Материал.373']} />
          <mesh name="Куб099_1" geometry={nodes.Куб099_1.geometry} material={materials['Материал.335']} />
        </group>
        <mesh name="Текст" geometry={nodes.Текст.geometry} material={nodes.Текст.material} position={[0.05, -0.12, 0.691]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.123, 0.146, 0.114]} />
        <mesh name="Текст001" geometry={nodes.Текст001.geometry} material={nodes.Текст001.material} position={[0.05, -0.12, 0.629]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.123, 0.146, 0.114]} />
        <mesh name="Текст002" geometry={nodes.Текст002.geometry} material={nodes.Текст002.material} position={[0.05, -0.121, 0.555]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.098, 0.146, 0.114]} />
        <mesh name="Текст003" geometry={nodes.Текст003.geometry} material={nodes.Текст003.material} position={[0.05, -0.121, 0.466]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.123, 0.146, 0.114]} />
        <group name="Плоскость020" position={[-0.257, 0.078, -1.043]} rotation={[Math.PI, 0, Math.PI / 2]}>
          <mesh name="Плоскость050" geometry={nodes.Плоскость050.geometry} material={materials['Материал.065']} />
          <mesh name="Плоскость050_1" geometry={nodes.Плоскость050_1.geometry} material={materials['Материал.004']} />
          <mesh name="Плоскость050_2" geometry={nodes.Плоскость050_2.geometry} material={materials['Материал.047']} />
          <mesh name="Плоскость050_3" geometry={nodes.Плоскость050_3.geometry} material={materials['Материал.049']} />
          <mesh name="Плоскость050_4" geometry={nodes.Плоскость050_4.geometry} material={materials['Материал.048']} />
          <mesh name="Плоскость050_5" geometry={nodes.Плоскость050_5.geometry} material={materials['Материал.053']} />
          <mesh name="Плоскость050_6" geometry={nodes.Плоскость050_6.geometry} material={materials['Материал.052']} />
          <mesh name="Плоскость050_7" geometry={nodes.Плоскость050_7.geometry} material={materials['Материал.051']} />
          <mesh name="Плоскость050_8" geometry={nodes.Плоскость050_8.geometry} material={materials['Материал.050']} />
          <mesh name="Плоскость050_9" geometry={nodes.Плоскость050_9.geometry} material={materials['Материал.061']} />
          <mesh name="Плоскость050_10" geometry={nodes.Плоскость050_10.geometry} material={materials['Материал.060']} />
          <mesh name="Плоскость050_11" geometry={nodes.Плоскость050_11.geometry} material={materials['Материал.059']} />
          <mesh name="Плоскость050_12" geometry={nodes.Плоскость050_12.geometry} material={materials['Материал.058']} />
          <mesh name="Плоскость050_13" geometry={nodes.Плоскость050_13.geometry} material={materials['Материал.057']} />
          <mesh name="Плоскость050_14" geometry={nodes.Плоскость050_14.geometry} material={materials['Материал.056']} />
          <mesh name="Плоскость050_15" geometry={nodes.Плоскость050_15.geometry} material={materials['Материал.055']} />
          <mesh name="Плоскость050_16" geometry={nodes.Плоскость050_16.geometry} material={materials['Материал.054']} />
          <mesh name="Плоскость050_17" geometry={nodes.Плоскость050_17.geometry} material={materials['Материал.069']} />
          <mesh name="Плоскость050_18" geometry={nodes.Плоскость050_18.geometry} material={materials['Материал.068']} />
          <mesh name="Плоскость050_19" geometry={nodes.Плоскость050_19.geometry} material={materials['Материал.067']} />
          <mesh name="Плоскость050_20" geometry={nodes.Плоскость050_20.geometry} material={materials['Материал.066']} />
          <mesh name="Плоскость050_21" geometry={nodes.Плоскость050_21.geometry} material={materials['Материал.064']} />
          <mesh name="Плоскость050_22" geometry={nodes.Плоскость050_22.geometry} material={materials['Материал.063']} />
          <mesh name="Плоскость050_23" geometry={nodes.Плоскость050_23.geometry} material={materials['Материал.062']} />
          <mesh name="Плоскость050_24" geometry={nodes.Плоскость050_24.geometry} material={materials['Материал.093']} />
          <mesh name="Плоскость050_25" geometry={nodes.Плоскость050_25.geometry} material={materials['Материал.092']} />
          <mesh name="Плоскость050_26" geometry={nodes.Плоскость050_26.geometry} material={materials['Материал.091']} />
          <mesh name="Плоскость050_27" geometry={nodes.Плоскость050_27.geometry} material={materials['Материал.090']} />
          <mesh name="Плоскость050_28" geometry={nodes.Плоскость050_28.geometry} material={materials['Материал.089']} />
          <mesh name="Плоскость050_29" geometry={nodes.Плоскость050_29.geometry} material={materials['Материал.088']} />
          <mesh name="Плоскость050_30" geometry={nodes.Плоскость050_30.geometry} material={materials['Материал.087']} />
          <mesh name="Плоскость050_31" geometry={nodes.Плоскость050_31.geometry} material={materials['Материал.086']} />
          <mesh name="Плоскость050_32" geometry={nodes.Плоскость050_32.geometry} material={materials['Материал.085']} />
          <mesh name="Плоскость050_33" geometry={nodes.Плоскость050_33.geometry} material={materials['Материал.084']} />
          <mesh name="Плоскость050_34" geometry={nodes.Плоскость050_34.geometry} material={materials['Материал.083']} />
          <mesh name="Плоскость050_35" geometry={nodes.Плоскость050_35.geometry} material={materials['Материал.082']} />
          <mesh name="Плоскость050_36" geometry={nodes.Плоскость050_36.geometry} material={materials['Материал.081']} />
          <mesh name="Плоскость050_37" geometry={nodes.Плоскость050_37.geometry} material={materials['Материал.080']} />
          <mesh name="Плоскость050_38" geometry={nodes.Плоскость050_38.geometry} material={materials['Материал.079']} />
          <mesh name="Плоскость050_39" geometry={nodes.Плоскость050_39.geometry} material={materials['Материал.078']} />
          <mesh name="Плоскость050_40" geometry={nodes.Плоскость050_40.geometry} material={materials['Материал.077']} />
          <mesh name="Плоскость050_41" geometry={nodes.Плоскость050_41.geometry} material={materials['Материал.076']} />
          <mesh name="Плоскость050_42" geometry={nodes.Плоскость050_42.geometry} material={materials['Материал.075']} />
          <mesh name="Плоскость050_43" geometry={nodes.Плоскость050_43.geometry} material={materials['Материал.074']} />
          <mesh name="Плоскость050_44" geometry={nodes.Плоскость050_44.geometry} material={materials['Материал.073']} />
          <mesh name="Плоскость050_45" geometry={nodes.Плоскость050_45.geometry} material={materials['Материал.072']} />
          <mesh name="Плоскость050_46" geometry={nodes.Плоскость050_46.geometry} material={materials['Материал.071']} />
          <mesh name="Плоскость050_47" geometry={nodes.Плоскость050_47.geometry} material={materials['Материал.070']} />
          <mesh name="Плоскость050_48" geometry={nodes.Плоскость050_48.geometry} material={materials['Материал.100']} />
          <mesh name="Плоскость050_49" geometry={nodes.Плоскость050_49.geometry} material={materials['Материал.096']} />
          <mesh name="Плоскость050_50" geometry={nodes.Плоскость050_50.geometry} material={materials['Материал.095']} />
          <mesh name="Плоскость050_51" geometry={nodes.Плоскость050_51.geometry} material={materials['Материал.094']} />
        </group>
        <group name="Вентилятор002" position={[-0.027, -0.069, -1.12]} rotation={[1.148, -0.002, -1.571]} scale={0.616} ref={fan2Ref}>
          <mesh name="Плоскость090" geometry={nodes.Плоскость090.geometry} material={materials['Материал.707']} />
          <mesh name="Плоскость090_1" geometry={nodes.Плоскость090_1.geometry} material={materials['Материал.706']} />
          <mesh name="Плоскость090_2" geometry={nodes.Плоскость090_2.geometry} material={materials['Материал.705']} />
          <mesh name="Плоскость090_3" geometry={nodes.Плоскость090_3.geometry} material={materials['Материал.704']} />
          <mesh name="Плоскость090_4" geometry={nodes.Плоскость090_4.geometry} material={materials['Материал.703']} />
          <mesh name="Плоскость090_5" geometry={nodes.Плоскость090_5.geometry} material={materials['Материал.702']} />
          <mesh name="Плоскость090_6" geometry={nodes.Плоскость090_6.geometry} material={materials['Материал.701']} />
          <mesh name="Плоскость090_7" geometry={nodes.Плоскость090_7.geometry} material={materials['Материал.700']} />
          <mesh name="Плоскость090_8" geometry={nodes.Плоскость090_8.geometry} material={materials['Материал.699']} />
          <mesh name="Плоскость090_9" geometry={nodes.Плоскость090_9.geometry} material={materials['Материал.698']} />
          <mesh name="Плоскость090_10" geometry={nodes.Плоскость090_10.geometry} material={materials['Материал.697']} />
        </group>
        <group name="Плоскость002" position={[0.034, 0.078, -1.056]} rotation={[Math.PI, 0, Math.PI / 2]}>
          <mesh name="Плоскость089" geometry={nodes.Плоскость089.geometry} material={materials['Материал.696']} />
          <mesh name="Плоскость089_1" geometry={nodes.Плоскость089_1.geometry} material={materials['Материал.695']} />
          <mesh name="Плоскость089_2" geometry={nodes.Плоскость089_2.geometry} material={materials['Материал.694']} />
          <mesh name="Плоскость089_3" geometry={nodes.Плоскость089_3.geometry} material={materials['Материал.693']} />
          <mesh name="Плоскость089_4" geometry={nodes.Плоскость089_4.geometry} material={materials['Материал.692']} />
          <mesh name="Плоскость089_5" geometry={nodes.Плоскость089_5.geometry} material={materials['Материал.691']} />
          <mesh name="Плоскость089_6" geometry={nodes.Плоскость089_6.geometry} material={materials['Материал.690']} />
          <mesh name="Плоскость089_7" geometry={nodes.Плоскость089_7.geometry} material={materials['Материал.689']} />
          <mesh name="Плоскость089_8" geometry={nodes.Плоскость089_8.geometry} material={materials['Материал.688']} />
          <mesh name="Плоскость089_9" geometry={nodes.Плоскость089_9.geometry} material={materials['Материал.687']} />
          <mesh name="Плоскость089_10" geometry={nodes.Плоскость089_10.geometry} material={materials['Материал.686']} />
          <mesh name="Плоскость089_11" geometry={nodes.Плоскость089_11.geometry} material={materials['Материал.685']} />
          <mesh name="Плоскость089_12" geometry={nodes.Плоскость089_12.geometry} material={materials['Материал.684']} />
          <mesh name="Плоскость089_13" geometry={nodes.Плоскость089_13.geometry} material={materials['Материал.683']} />
          <mesh name="Плоскость089_14" geometry={nodes.Плоскость089_14.geometry} material={materials['Материал.682']} />
          <mesh name="Плоскость089_15" geometry={nodes.Плоскость089_15.geometry} material={materials['Материал.681']} />
          <mesh name="Плоскость089_16" geometry={nodes.Плоскость089_16.geometry} material={materials['Материал.680']} />
          <mesh name="Плоскость089_17" geometry={nodes.Плоскость089_17.geometry} material={materials['Материал.679']} />
          <mesh name="Плоскость089_18" geometry={nodes.Плоскость089_18.geometry} material={materials['Материал.678']} />
          <mesh name="Плоскость089_19" geometry={nodes.Плоскость089_19.geometry} material={materials['Материал.677']} />
          <mesh name="Плоскость089_20" geometry={nodes.Плоскость089_20.geometry} material={materials['Материал.676']} />
          <mesh name="Плоскость089_21" geometry={nodes.Плоскость089_21.geometry} material={materials['Материал.675']} />
          <mesh name="Плоскость089_22" geometry={nodes.Плоскость089_22.geometry} material={materials['Материал.674']} />
          <mesh name="Плоскость089_23" geometry={nodes.Плоскость089_23.geometry} material={materials['Материал.673']} />
          <mesh name="Плоскость089_24" geometry={nodes.Плоскость089_24.geometry} material={materials['Материал.672']} />
          <mesh name="Плоскость089_25" geometry={nodes.Плоскость089_25.geometry} material={materials['Материал.671']} />
          <mesh name="Плоскость089_26" geometry={nodes.Плоскость089_26.geometry} material={materials['Материал.670']} />
          <mesh name="Плоскость089_27" geometry={nodes.Плоскость089_27.geometry} material={materials['Материал.669']} />
          <mesh name="Плоскость089_28" geometry={nodes.Плоскость089_28.geometry} material={materials['Материал.668']} />
          <mesh name="Плоскость089_29" geometry={nodes.Плоскость089_29.geometry} material={materials['Материал.667']} />
          <mesh name="Плоскость089_30" geometry={nodes.Плоскость089_30.geometry} material={materials['Материал.666']} />
          <mesh name="Плоскость089_31" geometry={nodes.Плоскость089_31.geometry} material={materials['Материал.665']} />
          <mesh name="Плоскость089_32" geometry={nodes.Плоскость089_32.geometry} material={materials['Материал.664']} />
          <mesh name="Плоскость089_33" geometry={nodes.Плоскость089_33.geometry} material={materials['Материал.663']} />
          <mesh name="Плоскость089_34" geometry={nodes.Плоскость089_34.geometry} material={materials['Материал.662']} />
          <mesh name="Плоскость089_35" geometry={nodes.Плоскость089_35.geometry} material={materials['Материал.661']} />
          <mesh name="Плоскость089_36" geometry={nodes.Плоскость089_36.geometry} material={materials['Материал.660']} />
          <mesh name="Плоскость089_37" geometry={nodes.Плоскость089_37.geometry} material={materials['Материал.659']} />
          <mesh name="Плоскость089_38" geometry={nodes.Плоскость089_38.geometry} material={materials['Материал.658']} />
          <mesh name="Плоскость089_39" geometry={nodes.Плоскость089_39.geometry} material={materials['Материал.657']} />
          <mesh name="Плоскость089_40" geometry={nodes.Плоскость089_40.geometry} material={materials['Материал.656']} />
          <mesh name="Плоскость089_41" geometry={nodes.Плоскость089_41.geometry} material={materials['Материал.655']} />
          <mesh name="Плоскость089_42" geometry={nodes.Плоскость089_42.geometry} material={materials['Материал.654']} />
          <mesh name="Плоскость089_43" geometry={nodes.Плоскость089_43.geometry} material={materials['Материал.653']} />
          <mesh name="Плоскость089_44" geometry={nodes.Плоскость089_44.geometry} material={materials['Материал.652']} />
          <mesh name="Плоскость089_45" geometry={nodes.Плоскость089_45.geometry} material={materials['Материал.651']} />
          <mesh name="Плоскость089_46" geometry={nodes.Плоскость089_46.geometry} material={materials['Материал.650']} />
          <mesh name="Плоскость089_47" geometry={nodes.Плоскость089_47.geometry} material={materials['Материал.649']} />
          <mesh name="Плоскость089_48" geometry={nodes.Плоскость089_48.geometry} material={materials['Материал.648']} />
          <mesh name="Плоскость089_49" geometry={nodes.Плоскость089_49.geometry} material={materials['Материал.647']} />
          <mesh name="Плоскость089_50" geometry={nodes.Плоскость089_50.geometry} material={materials['Материал.646']} />
          <mesh name="Плоскость089_51" geometry={nodes.Плоскость089_51.geometry} material={materials['Материал.645']} />
        </group>
        <mesh name="Цилиндр001" geometry={nodes.Цилиндр001.geometry} material={materials['Материал.644']} position={[0.478, -0.069, -1.118]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.487, 0.61, 0.487]} />
        <mesh name="Плоскость003" geometry={nodes.Плоскость003.geometry} material={materials['Материал.002']} position={[-0.104, 0.082, -1.028]} rotation={[0, 0, -Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <mesh name="Плоскость004" geometry={nodes.Плоскость004.geometry} material={materials['Материал.708']} position={[-0.104, -0.248, -1.028]} rotation={[0, 0, -Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <mesh name="Плоскость005" geometry={nodes.Плоскость005.geometry} material={materials['Материал.709']} position={[-0.104, 0.28, -1.028]} rotation={[0, 0, -Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <mesh name="Плоскость006" geometry={nodes.Плоскость006.geometry} material={materials['Материал.710']} position={[-0.104, -0.445, -1.028]} rotation={[0, 0, -Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <group name="Плоскость010" position={[-0.259, 0.078, 0.497]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Плоскость105" geometry={nodes.Плоскость105.geometry} material={materials['Материал.835']} />
          <mesh name="Плоскость105_1" geometry={nodes.Плоскость105_1.geometry} material={materials['Материал.834']} />
          <mesh name="Плоскость105_2" geometry={nodes.Плоскость105_2.geometry} material={materials['Материал.833']} />
          <mesh name="Плоскость105_3" geometry={nodes.Плоскость105_3.geometry} material={materials['Материал.832']} />
          <mesh name="Плоскость105_4" geometry={nodes.Плоскость105_4.geometry} material={materials['Материал.831']} />
          <mesh name="Плоскость105_5" geometry={nodes.Плоскость105_5.geometry} material={materials['Материал.830']} />
          <mesh name="Плоскость105_6" geometry={nodes.Плоскость105_6.geometry} material={materials['Материал.829']} />
          <mesh name="Плоскость105_7" geometry={nodes.Плоскость105_7.geometry} material={materials['Материал.828']} />
          <mesh name="Плоскость105_8" geometry={nodes.Плоскость105_8.geometry} material={materials['Материал.827']} />
          <mesh name="Плоскость105_9" geometry={nodes.Плоскость105_9.geometry} material={materials['Материал.826']} />
          <mesh name="Плоскость105_10" geometry={nodes.Плоскость105_10.geometry} material={materials['Материал.825']} />
          <mesh name="Плоскость105_11" geometry={nodes.Плоскость105_11.geometry} material={materials['Материал.824']} />
          <mesh name="Плоскость105_12" geometry={nodes.Плоскость105_12.geometry} material={materials['Материал.823']} />
          <mesh name="Плоскость105_13" geometry={nodes.Плоскость105_13.geometry} material={materials['Материал.822']} />
          <mesh name="Плоскость105_14" geometry={nodes.Плоскость105_14.geometry} material={materials['Материал.821']} />
          <mesh name="Плоскость105_15" geometry={nodes.Плоскость105_15.geometry} material={materials['Материал.820']} />
          <mesh name="Плоскость105_16" geometry={nodes.Плоскость105_16.geometry} material={materials['Материал.819']} />
          <mesh name="Плоскость105_17" geometry={nodes.Плоскость105_17.geometry} material={materials['Материал.818']} />
          <mesh name="Плоскость105_18" geometry={nodes.Плоскость105_18.geometry} material={materials['Материал.817']} />
          <mesh name="Плоскость105_19" geometry={nodes.Плоскость105_19.geometry} material={materials['Материал.816']} />
          <mesh name="Плоскость105_20" geometry={nodes.Плоскость105_20.geometry} material={materials['Материал.815']} />
          <mesh name="Плоскость105_21" geometry={nodes.Плоскость105_21.geometry} material={materials['Материал.814']} />
          <mesh name="Плоскость105_22" geometry={nodes.Плоскость105_22.geometry} material={materials['Материал.813']} />
          <mesh name="Плоскость105_23" geometry={nodes.Плоскость105_23.geometry} material={materials['Материал.812']} />
          <mesh name="Плоскость105_24" geometry={nodes.Плоскость105_24.geometry} material={materials['Материал.811']} />
          <mesh name="Плоскость105_25" geometry={nodes.Плоскость105_25.geometry} material={materials['Материал.810']} />
          <mesh name="Плоскость105_26" geometry={nodes.Плоскость105_26.geometry} material={materials['Материал.809']} />
          <mesh name="Плоскость105_27" geometry={nodes.Плоскость105_27.geometry} material={materials['Материал.808']} />
          <mesh name="Плоскость105_28" geometry={nodes.Плоскость105_28.geometry} material={materials['Материал.807']} />
          <mesh name="Плоскость105_29" geometry={nodes.Плоскость105_29.geometry} material={materials['Материал.806']} />
          <mesh name="Плоскость105_30" geometry={nodes.Плоскость105_30.geometry} material={materials['Материал.805']} />
          <mesh name="Плоскость105_31" geometry={nodes.Плоскость105_31.geometry} material={materials['Материал.804']} />
          <mesh name="Плоскость105_32" geometry={nodes.Плоскость105_32.geometry} material={materials['Материал.803']} />
          <mesh name="Плоскость105_33" geometry={nodes.Плоскость105_33.geometry} material={materials['Материал.802']} />
          <mesh name="Плоскость105_34" geometry={nodes.Плоскость105_34.geometry} material={materials['Материал.801']} />
          <mesh name="Плоскость105_35" geometry={nodes.Плоскость105_35.geometry} material={materials['Материал.800']} />
          <mesh name="Плоскость105_36" geometry={nodes.Плоскость105_36.geometry} material={materials['Материал.799']} />
          <mesh name="Плоскость105_37" geometry={nodes.Плоскость105_37.geometry} material={materials['Материал.798']} />
          <mesh name="Плоскость105_38" geometry={nodes.Плоскость105_38.geometry} material={materials['Материал.797']} />
          <mesh name="Плоскость105_39" geometry={nodes.Плоскость105_39.geometry} material={materials['Материал.796']} />
          <mesh name="Плоскость105_40" geometry={nodes.Плоскость105_40.geometry} material={materials['Материал.795']} />
          <mesh name="Плоскость105_41" geometry={nodes.Плоскость105_41.geometry} material={materials['Материал.794']} />
          <mesh name="Плоскость105_42" geometry={nodes.Плоскость105_42.geometry} material={materials['Материал.793']} />
          <mesh name="Плоскость105_43" geometry={nodes.Плоскость105_43.geometry} material={materials['Материал.792']} />
          <mesh name="Плоскость105_44" geometry={nodes.Плоскость105_44.geometry} material={materials['Материал.791']} />
          <mesh name="Плоскость105_45" geometry={nodes.Плоскость105_45.geometry} material={materials['Материал.790']} />
          <mesh name="Плоскость105_46" geometry={nodes.Плоскость105_46.geometry} material={materials['Материал.789']} />
          <mesh name="Плоскость105_47" geometry={nodes.Плоскость105_47.geometry} material={materials['Материал.788']} />
          <mesh name="Плоскость105_48" geometry={nodes.Плоскость105_48.geometry} material={materials['Материал.787']} />
          <mesh name="Плоскость105_49" geometry={nodes.Плоскость105_49.geometry} material={materials['Материал.786']} />
          <mesh name="Плоскость105_50" geometry={nodes.Плоскость105_50.geometry} material={materials['Материал.785']} />
          <mesh name="Плоскость105_51" geometry={nodes.Плоскость105_51.geometry} material={materials['Материал.784']} />
        </group>
        <mesh name="Плоскость009" geometry={nodes.Плоскость009.geometry} material={materials['Материал.783']} position={[-0.12, 0.082, 0.469]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <mesh name="Плоскость008" geometry={nodes.Плоскость008.geometry} material={materials['Материал.782']} position={[-0.12, -0.248, 0.469]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <mesh name="Плоскость007" geometry={nodes.Плоскость007.geometry} material={materials['Материал.781']} position={[-0.12, 0.28, 0.469]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <mesh name="Плоскость001" geometry={nodes.Плоскость001.geometry} material={materials['Материал.780']} position={[-0.12, -0.445, 0.469]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.047, 0.583, 0.583]} />
        <mesh name="Цилиндр002" geometry={nodes.Цилиндр002.geometry} material={materials['Материал.779']} position={[-0.703, -0.069, 0.559]} rotation={[0, 0, -Math.PI / 2]} scale={[0.487, 0.61, 0.487]} />
        <mesh name="Плоскость011" geometry={nodes.Плоскость011.geometry} material={materials['Материал.011']} position={[0.145, -0.047, 1.093]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.875} />
        <group name="Плоскость012" position={[-0.011, -0.042, 0.163]} rotation={[0, 0, -Math.PI / 2]} scale={0.719}>
          <mesh name="Плоскость109" geometry={nodes.Плоскость109.geometry} material={materials['Материал.002']} />
          <mesh name="Плоскость109_1" geometry={nodes.Плоскость109_1.geometry} material={materials['Материал.007']} />
        </group>
        <group name="Вентилятор001" position={[-0.205, -0.065, 0.561]} rotation={[1.993, 0.002, 1.57]} scale={0.616} ref={fan1Ref}>
          <mesh name="Плоскость110" geometry={nodes.Плоскость110.geometry} material={materials['Материал.859']} />
          <mesh name="Плоскость110_1" geometry={nodes.Плоскость110_1.geometry} material={materials['Материал.858']} />
          <mesh name="Плоскость110_2" geometry={nodes.Плоскость110_2.geometry} material={materials['Материал.857']} />
          <mesh name="Плоскость110_3" geometry={nodes.Плоскость110_3.geometry} material={materials['Материал.856']} />
          <mesh name="Плоскость110_4" geometry={nodes.Плоскость110_4.geometry} material={materials['Материал.855']} />
          <mesh name="Плоскость110_5" geometry={nodes.Плоскость110_5.geometry} material={materials['Материал.854']} />
          <mesh name="Плоскость110_6" geometry={nodes.Плоскость110_6.geometry} material={materials['Материал.853']} />
          <mesh name="Плоскость110_7" geometry={nodes.Плоскость110_7.geometry} material={materials['Материал.852']} />
          <mesh name="Плоскость110_8" geometry={nodes.Плоскость110_8.geometry} material={materials['Материал.851']} />
          <mesh name="Плоскость110_9" geometry={nodes.Плоскость110_9.geometry} material={materials['Материал.850']} />
          <mesh name="Плоскость110_10" geometry={nodes.Плоскость110_10.geometry} material={materials['Материал.849']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/video-card.glb')
