/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Y70.glb 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
 
  const { nodes, materials } = useGLTF('/Y70.glb')
  console.log("!!!node", nodes)
  console.log("!!!materials", materials)

  
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <group position={[80.1, 212.758, -246.768]} rotation={[0.009, 0, -Math.PI / 2]}>
          <mesh geometry={nodes['PA-Y206-MINI-HUB_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
          <mesh geometry={nodes['PA-Y206-MINI-HUB_2'].geometry} material={materials.OLIVEDRAB2} />
        </group>
        <group position={[59, 19, -70]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
          <mesh geometry={nodes['3-12CM-WATERCOOLER-30H-DEEPCOOL'].geometry} material={materials.OLIVEDRAB2} position={[364.5, -169, 80]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes['FAN-120004'].geometry} material={materials.CYAN4} position={[364.3, -49, 37.5]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['FAN-120005'].geometry} material={materials.CYAN4} position={[364.3, -169, 37.5]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['FAN-120006'].geometry} material={materials.CYAN4} position={[364.3, -289, 37.5]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['GROMMET-NEW-6-30'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-19.05, 70, -59]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          <group position={[297, 18, 80.7]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes['RG-PANEL-SUPPORT-CA-Y302_1'].geometry} material={materials.RED} />
            <mesh geometry={nodes['RG-PANEL-SUPPORT-CA-Y302_2'].geometry} material={materials.LIGHTSTEELBLUE2} />
          </group>
        </group>
        <mesh geometry={nodes['bottom-cover-ca-y302-1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['EPE-PCIE-CA-Y302'].geometry} material={materials.LIMEGREEN} position={[-41.21, 129.823, -240.5]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['FRONT-LCD-CVOER-CA-Y307'].geometry} material={materials.LIGHTCYAN} />
        <mesh geometry={nodes['MB-SUPPORT-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[58.7, 19, -70]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201'].geometry} material={materials.MAROON2} position={[-145, 23, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201001'].geometry} material={materials.MAROON2} position={[-145, 355, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201002'].geometry} material={materials.MAROON2} position={[-136.213, 382.574, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201003'].geometry} material={materials.MAROON2} position={[-72.574, 446.213, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201004'].geometry} material={materials.MAROON2} position={[-40, 455, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201005'].geometry} material={materials.MAROON2} position={[40, 455, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201006'].geometry} material={materials.MAROON2} position={[120, 455, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201007'].geometry} material={materials.MAROON2} position={[-145, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201008'].geometry} material={materials.MAROON2} position={[-140, 0.7, -32]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201009'].geometry} material={materials.MAROON2} position={[-40, 0.7, -32]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201010'].geometry} material={materials.MAROON2} position={[40, 0.7, -32]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201011'].geometry} material={materials.MAROON2} position={[135, 6.7, -50.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201012'].geometry} material={materials.MAROON2} position={[80, 6.7, -50.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201013'].geometry} material={materials.MAROON2} position={[65, 6.7, -50.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201014'].geometry} material={materials.MAROON2} position={[145, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201015'].geometry} material={materials.MAROON2} position={[50, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201016'].geometry} material={materials.MAROON2} position={[-50, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201017'].geometry} material={materials.MAROON2} position={[130, 9.4, -351.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201018'].geometry} material={materials.MAROON2} position={[105, 9.4, -351.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201019'].geometry} material={materials.MAROON2} position={[80, 9.4, -351.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201020'].geometry} material={materials.MAROON2} position={[130, 9.4, -232.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201021'].geometry} material={materials.MAROON2} position={[105, 9.4, -232.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201022'].geometry} material={materials.MAROON2} position={[80, 9.4, -232.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201023'].geometry} material={materials.MAROON2} position={[65, 6.7, -395]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201024'].geometry} material={materials.MAROON2} position={[65, 6.7, -290]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201025'].geometry} material={materials.MAROON2} position={[65, 6.7, -214]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201026'].geometry} material={materials.MAROON2} position={[139, 320, -40]} rotation={[-1.451, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201027'].geometry} material={materials.MAROON2} position={[139, 439, -40]} rotation={[-1.451, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201028'].geometry} material={materials.MAROON2} position={[135, 437, -0.7]} rotation={[-Math.PI, 0, -1.588]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201029'].geometry} material={materials.MAROON2} position={[135, 329, -0.7]} rotation={[-Math.PI, 0, -1.588]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201030'].geometry} material={materials.MAROON2} position={[124, 307, -0.7]} rotation={[-Math.PI, 0, -1.588]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201043'].geometry} material={materials.MAROON2} position={[139, 0.7, -449]} rotation={[-Math.PI / 2, 0, -1.408]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201044'].geometry} material={materials.MAROON2} position={[55, 0.7, -449]} rotation={[-Math.PI / 2, 0, -1.408]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201045'].geometry} material={materials.MAROON2} position={[-55, 0.7, -449]} rotation={[-Math.PI / 2, 0, -1.408]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201046'].geometry} material={materials.MAROON2} position={[-139, 0.7, -449]} rotation={[-Math.PI / 2, 0, -1.408]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201047'].geometry} material={materials.MAROON2} position={[-139, 0.7, -438.2]} rotation={[-Math.PI / 2, 0, -1.408]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201048'].geometry} material={materials.MAROON2} position={[64, 50, -457.3]} rotation={[0, 0, -1.516]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201049'].geometry} material={materials.MAROON2} position={[64, 200, -457.3]} rotation={[0, 0, -1.516]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201050'].geometry} material={materials.MAROON2} position={[133.7, 324.584, -457.3]} rotation={[0, 0, -1.516]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201051'].geometry} material={materials.MAROON2} position={[133.7, 426.584, -457.3]} rotation={[0, 0, -1.516]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-4'].geometry} material={materials.WHITESMOKE} position={[146.5, 26, -1.9]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-4001'].geometry} material={materials.WHITESMOKE} position={[146.5, 163, -1.9]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-4002'].geometry} material={materials.WHITESMOKE} position={[146.5, 300, -1.9]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-4003'].geometry} material={materials.WHITESMOKE} position={[146.5, 437, -1.9]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-5'].geometry} material={materials.WHITESMOKE} position={[120, 301.8, -40]} rotation={[-Math.PI / 2, 0, -0.003]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-5001'].geometry} material={materials.WHITESMOKE} position={[59.7, 240, -40]} rotation={[-1.448, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-5002'].geometry} material={materials.WHITESMOKE} position={[59.7, 149, -40]} rotation={[-1.448, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-5003'].geometry} material={materials.WHITESMOKE} position={[59.7, 44, -40]} rotation={[-1.448, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-5004'].geometry} material={materials.WHITESMOKE} position={[139.7, 453, -447.4]} rotation={[-1.448, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-5005'].geometry} material={materials.WHITESMOKE} position={[139.7, 453, -435.4]} rotation={[-1.448, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-7'].geometry} material={materials.WHITESMOKE} position={[103.716, 65.385, 2.5]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-7001'].geometry} material={materials.WHITESMOKE} position={[0, 18, 2.5]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-7002'].geometry} material={materials.WHITESMOKE} position={[-102, 18, 2.5]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-7003'].geometry} material={materials.WHITESMOKE} position={[102, 437, 2.5]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-7004'].geometry} material={materials.WHITESMOKE} position={[0, 437, 2.5]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-7005'].geometry} material={materials.WHITESMOKE} position={[-103.716, 389.615, 2.5]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['THUMBS-SCREW-6-32'].geometry} material={materials.ORANGERED2} position={[69, 95, -448.9]} rotation={[2.915, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['THUMBS-SCREW-6-32001'].geometry} material={materials.ORANGERED2} position={[69, 230, -448.9]} rotation={[2.915, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['THUMBS-SCREW-6-32002'].geometry} material={materials.ORANGERED2} position={[69, 95, -430.3]} rotation={[2.915, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['THUMBS-SCREW-6-32003'].geometry} material={materials.ORANGERED2} position={[69, 230, -430.3]} rotation={[2.915, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.UM_PROD_BODY.geometry} material={materials.STEP_ff00ff} />
        <mesh geometry={nodes['BOTTOM-COVER-CA-Y302'].geometry} material={materials.GREEN} />
        <mesh geometry={nodes['BOTTOM-FILTER-CA-Y302'].geometry} material={materials.LIGHTSALMON3} position={[0, 0, 0.4]} />
        <mesh geometry={nodes['POWER-SUPPORT-CA-Y302'].geometry} material={materials.GRAY67} />
        <mesh geometry={nodes['VELCRO-B-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[95, 100, -1.2]} />
        <mesh geometry={nodes['VELCRO-B-CA-Y302001'].geometry} material={materials.LIGHTSTEELBLUE2} position={[95, 190, -1.2]} />
        <mesh geometry={nodes['VELCRO-B-CA-Y302002'].geometry} material={materials.LIGHTSTEELBLUE2} position={[95, 280, -1.2]} />
        <mesh geometry={nodes['BOTTOM-PLASTIC-CA-Y302'].geometry} material={materials.GRAY62} />
        <mesh geometry={nodes['BOTTOM-RUBBER-CA-Y302_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['BOTTOM-RUBBER-CA-Y302_2'].geometry} material={materials.GRAY62} />
        <mesh geometry={nodes['FAN-120'].geometry} material={materials.CYAN4} position={[-82, 76, -15]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh geometry={nodes['FAN-120001'].geometry} material={materials.CYAN4} position={[-82, 196, -15]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh geometry={nodes['FAN-120002'].geometry} material={materials.CYAN4} position={[-82, 316, -15]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
        <mesh geometry={nodes['FAN-140X25'].geometry} material={materials.CYAN4} position={[-72, 104, -15]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['FAN-140X25001'].geometry} material={materials.CYAN4} position={[-72, 244, -15]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['FAN-BRACKET-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['SCREW-FAN'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-134.5, 128.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN001'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-29.5, 128.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN002'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-134.5, 143.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN003'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-29.5, 143.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN004'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-134.5, 248.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN005'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-29.5, 248.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN006'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-134.5, 263.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN007'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-29.5, 263.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-FAN008'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-29.5, 368.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101'].geometry} material={materials.GRAY62} position={[18, 70, 3.5]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101001'].geometry} material={materials.GRAY62} position={[18, 230, 3.5]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101002'].geometry} material={materials.GRAY62} position={[18, 390, 3.5]} rotation={[Math.PI, 0, Math.PI]} />
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-103.123, 21.6, 415.664]} rotation={[-Math.PI / 2, 0, 2.356]}>
            <group position={[-0.6, 0, -5]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['1206-CA-Y302_AF0_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
              <mesh geometry={nodes['1206-CA-Y302_AF0_2'].geometry} material={materials.LIMEGREEN} />
            </group>
            <group position={[-9, 0, 6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes['1206-CA-Y302_AF1_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
              <mesh geometry={nodes['1206-CA-Y302_AF1_2'].geometry} material={materials.LIMEGREEN} />
            </group>
            <group position={[9, 0, 6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes['1206-CA-Y302_AF2_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
              <mesh geometry={nodes['1206-CA-Y302_AF2_2'].geometry} material={materials.LIMEGREEN} />
            </group>
            <group position={[-9, 0, -6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes['1206-CA-Y302_AF3_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
              <mesh geometry={nodes['1206-CA-Y302_AF3_2'].geometry} material={materials.LIMEGREEN} />
            </group>
            <group position={[9, 0, -6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes['1206-CA-Y302_AF4_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
              <mesh geometry={nodes['1206-CA-Y302_AF4_2'].geometry} material={materials.LIMEGREEN} />
            </group>
            <mesh geometry={nodes['AUDIO-JACK-PHANTOM410_AF3'].geometry} material={materials.LIGHTSTEELBLUE3} position={[40, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
            <mesh geometry={nodes['CON-USB-3-0-NEW_AF2'].geometry} material={materials.WHITESMOKE} position={[22.75, 1.25, 0]} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes['CON-USB-3-0-NEW_AF3'].geometry} material={materials.WHITESMOKE} position={[-22.75, 1.25, 0]} rotation={[0, -Math.PI / 2, 0]} />
            <mesh geometry={nodes['KS-27H10B050NN-X5_2_1_AF0'].geometry} material={materials.DARKGOLDENROD} position={[0, 3, 0]} rotation={[-Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes['PCB-CA-Y302_AF0'].geometry} material={materials.GOLDENROD1} />
            <mesh geometry={nodes['TYPC-180_AF5'].geometry} material={materials.WHITESMOKE} position={[-40, 15, 0]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0'].geometry} material={materials.PLUM2} position={[33, -1.6, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
            <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0'].geometry} material={materials.PLUM2} position={[0, -1.6, 10.9]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-110.76, 21.6, 423.301]} rotation={[Math.PI / 2, 0, Math.PI / 4]}>
            <mesh geometry={nodes['CUT-REVOLVE1'].geometry} material={materials.GRAY62} />
            <mesh geometry={nodes.COMBINE6_1.geometry} material={materials.LIMEGREEN} />
            <mesh geometry={nodes.COMBINE6_2.geometry} material={materials.LIGHTSTEELBLUE2} />
          </group>
        </group>
        <mesh geometry={nodes['BOTTOM-RING-CA-Y302'].geometry} material={materials.LIGHTSALMON3} />
        <mesh geometry={nodes['GLASS-SUPPORT-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-153, 314, -28.4]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes['GLASS-SUPPORT-CA-Y302001'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-20, 463, -28.4]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes['GLASS-SUPPORT-CA-Y302002'].geometry} material={materials.LIGHTSTEELBLUE2} position={[110, 463, -28.4]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes['GLASS-SUPPORT-V2-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-153, 14, -28.4]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes['PCIE-PLASTIC-SUPPORT-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-25, 93, -38.31]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['BOTTOM-PANEL-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['BOTTOM-PANEL-V3-CA-Y302'].geometry} material={materials.GRAY77} />
        <group position={[-110.156, 419.944, -235.2]} rotation={[Math.PI / 2, Math.PI / 4, -Math.PI / 2]}>
          <mesh geometry={nodes['NV140DQM-N51'].geometry} material={materials.CORAL3} />
          <mesh geometry={nodes['TP-GLASS-CA-Y307'].geometry} material={materials.GRAY90} position={[0, 0, -1]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <mesh geometry={nodes['SCREW-F-UNC6-32-4004'].geometry} material={materials.WHITESMOKE} position={[-76.251, 435.748, -424.4]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['SCREW-F-UNC6-32-4005'].geometry} material={materials.WHITESMOKE} position={[-125.748, 386.25, -424.4]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['FRONT-GLASS-45-CA-Y302'].geometry} material={materials.LIGHTCYAN} />
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['FRONT-GLASS-BRACKET-45-CA-Y302_1'].geometry} material={materials.RED} />
          <mesh geometry={nodes['FRONT-GLASS-BRACKET-45-CA-Y302_2'].geometry} material={materials.LIGHTCYAN} />
        </group>
        <mesh geometry={nodes['FRONT-GLASS-BRACKET-B-CA-Y302'].geometry} material={materials.LIGHTCYAN} rotation={[-Math.PI / 2, 0, 0]} />
        <group position={[-100.363, 410.363, -327.05]} rotation={[Math.PI / 2, Math.PI / 4, -Math.PI]}>
          <mesh geometry={nodes['LH-W25B-AV1'].geometry} material={materials.PERU} />
          <mesh geometry={nodes['MINI-DP-7-6'].geometry} material={materials.LIGHTCYAN} position={[13.05, 24.4, -1.35]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes['TYPE-C-CABLE-180'].geometry} material={materials.GRAY59} position={[-17.85, 25.25, -1.755]} rotation={[Math.PI / 2, 0, -Math.PI]} />
        </group>
        <mesh geometry={nodes['FRONT-LCD-CVOER-B-CA-Y307'].geometry} material={materials.LIGHTCYAN} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['LCD-EMI-CVOER-A-CA-Y307'].geometry} material={materials.IVORY} position={[-106.373, 416.373, -358.1]} rotation={[-Math.PI / 2, -Math.PI / 4, -Math.PI]} />
        <mesh geometry={nodes['SCREW-M3_L5'].geometry} material={materials.WHITESMOKE} position={[-130.061, 380.664, -349.05]} rotation={[-Math.PI / 2, -Math.PI / 4, 2.649]} />
        <mesh geometry={nodes['SCREW-M3_L5001'].geometry} material={materials.WHITESMOKE} position={[-70.664, 440.061, -349.05]} rotation={[-Math.PI / 2, -Math.PI / 4, 2.649]} />
        <mesh geometry={nodes['SCREW-M3_L5002'].geometry} material={materials.WHITESMOKE} position={[-130.061, 380.664, -300.05]} rotation={[-Math.PI / 2, -Math.PI / 4, 2.649]} />
        <mesh geometry={nodes['SCREW-M3_L5003'].geometry} material={materials.WHITESMOKE} position={[-70.664, 440.061, -300.05]} rotation={[-Math.PI / 2, -Math.PI / 4, 2.649]} />
        <group position={[0, 463.2, -434.3]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes['FRONT-GLASS-BRACKET-CA-Y302'].geometry} material={materials.GRAY62} />
          <mesh geometry={nodes['STANDOFF-SO-2-CA-Y302'].geometry} material={materials.LIGHTCYAN} position={[-0.6, -30, 4.5]} rotation={[0, -Math.PI / 2, 0]} />
        </group>
        <mesh geometry={nodes['FRONT-GLASS-CA-Y302_1'].geometry} material={materials.LIGHTCYAN} />
        <mesh geometry={nodes['FRONT-GLASS-CA-Y302_2'].geometry} material={materials.GRAY59} />
        <group position={[-153.2, 0, -435]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['STANDOFF-SO-2-CA-Y302001'].geometry} material={materials.LIGHTCYAN} position={[-0.7, -5.2, 60]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['STANDOFF-SO-2-CA-Y302002'].geometry} material={materials.LIGHTCYAN} position={[-0.7, -5.2, 300]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['LF-GLASS-BRACKET-CA-Y302'].geometry} material={materials.GRAY62} />
          <mesh geometry={nodes['TU-RG-PANEL-CA-Y302'].geometry} material={materials.LIGHTCYAN} position={[-0.7, -5.2, 73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['TU-RG-PANEL-CA-Y302001'].geometry} material={materials.LIGHTCYAN} position={[-0.7, -5.2, 313]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        </group>
        <mesh geometry={nodes['LF-GLASS-CA-Y302_1'].geometry} material={materials.LIGHTCYAN} />
        <mesh geometry={nodes['LF-GLASS-CA-Y302_2'].geometry} material={materials.GRAY59} />
        <group position={[7.27, 7.5, -67.1]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
          <mesh geometry={nodes['DP-BRACKET-CA-Y307'].geometry} material={materials.LIGHTSTEELBLUE2} position={[0, 0, -40.73]} rotation={[-Math.PI, 0, Math.PI / 2]} />
          <mesh geometry={nodes.DP_RECEPTACAL.geometry} material={materials.LIGHTSTEELBLUE2} />
        </group>
        <group position={[106.3, 6, -292]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101003'].geometry} material={materials.GRAY62} position={[59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101004'].geometry} material={materials.GRAY62} position={[-59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['HDD-TRAY-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} />
          <mesh geometry={nodes.SERIAL_ATA_HD_3.geometry} material={materials.DARKSEAGREEN1} position={[50.8, 14.25, -3]} rotation={[0, 0, Math.PI]} />
        </group>
        <group position={[75.4, 6, -292]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101005'].geometry} material={materials.GRAY62} position={[59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101006'].geometry} material={materials.GRAY62} position={[-59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['HDD-TRAY-CA-Y302001'].geometry} material={materials.LIGHTSTEELBLUE2} />
          <mesh geometry={nodes.SERIAL_ATA_HD_3001.geometry} material={materials.DARKSEAGREEN1} position={[50.8, 14.25, -3]} rotation={[0, 0, Math.PI]} />
        </group>
        <group position={[-48.21, 8.36, -48.35]}>
          <group position={[1.75, 43.06, 2.52]}>
            <mesh geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101_1'].geometry} material={materials.GRAY65} />
            <mesh geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101_2'].geometry} material={materials.LIMEGREEN} />
            <mesh geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101_3'].geometry} material={materials.DEEPSKYBLUE4} />
          </group>
          <group position={[28.5, 0, -143.5]}>
            <mesh geometry={nodes['BKT-PCIE-PLASTIC-BASE-CA-Y101_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
            <mesh geometry={nodes['BKT-PCIE-PLASTIC-BASE-CA-Y101_2'].geometry} material={materials.GRAY62} />
          </group>
          <group position={[28.5, 0, -143.5]}>
            <mesh geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_2_1'].geometry} material={materials.GRAY64} />
            <mesh geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_2_2'].geometry} material={materials.LIGHTSTEELBLUE2} />
          </group>
          <mesh geometry={nodes['VGA-CARD-ATI'].geometry} material={materials.CADETBLUE1} />
        </group>
        <mesh geometry={nodes['FAN-120003'].geometry} material={materials.CYAN4} position={[-55, 19.2, -299]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes['BKT-HDD-CA-Y302'].geometry} material={materials.LIGHTGOLDENROD2} position={[74.7, 10.3, -292]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-CA-Y201'].geometry} material={materials.LIMEGREEN} position={[48, 7.3, -189]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-CA-Y201001'].geometry} material={materials.LIMEGREEN} position={[48, 7.3, -168.68]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-CA-Y201002'].geometry} material={materials.LIMEGREEN} position={[48, 7.3, -148.36]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-CA-Y201003'].geometry} material={materials.LIMEGREEN} position={[48, 7.3, -128.04]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-CA-Y201004'].geometry} material={materials.LIMEGREEN} position={[48, 7.3, -107.72]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-CA-Y201005'].geometry} material={materials.LIMEGREEN} position={[48, 7.3, -87.4]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-CA-Y201006'].geometry} material={materials.LIMEGREEN} position={[48, 7.3, -67.08]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201'].geometry} material={materials.LIMEGREEN} position={[-54.75, 7.37, -50.5]} />
        <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201001'].geometry} material={materials.LIMEGREEN} position={[-75.07, 7.37, -50.5]} />
        <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201002'].geometry} material={materials.LIMEGREEN} position={[-95.39, 7.37, -50.5]} />
        <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201003'].geometry} material={materials.LIMEGREEN} position={[-115.71, 7.37, -50.5]} />
        <mesh geometry={nodes['PSU-BRACKET-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[60, 6.9, -55.5]} />
        <group position={[64.4, 76.7, -108]} rotation={[-Math.PI, -1.571, 0]}>
          <mesh geometry={nodes['PSU-D185_1'].geometry} material={materials.WHITESMOKE} />
          <mesh geometry={nodes['PSU-D185_2'].geometry} material={materials.TOMATO2} />
          <mesh geometry={nodes['PSU-D185_3'].geometry} material={materials.GRAY28} />
        </group>
        <mesh geometry={nodes['REAR-PANEL-CA-Y302'].geometry} material={materials.GRAY62} />
        <mesh geometry={nodes['RG-PANEL-CA-Y302'].geometry} material={materials.GOLDENROD1} />
        <mesh geometry={nodes['STANDOFF-SO-CA-Y101'].geometry} material={materials.LIGHTSTEELBLUE2} position={[152.2, 100, -447.8]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['STANDOFF-SO-CA-Y101001'].geometry} material={materials.LIGHTSTEELBLUE2} position={[152.2, 380, -447.8]} rotation={[0, 1.571, 0]} />
        <mesh geometry={nodes['RG-PANEL-FILTER-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-0.3, 0, 0]} />
        <mesh geometry={nodes['TOP-COVER-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['TOP-COVER-PLASTIC-CA-Y302_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['TOP-COVER-PLASTIC-CA-Y302_2'].geometry} material={materials.LIMEGREEN} />
        <group position={[1, 8, -457.2]} rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes['FAN-BRACKET-TOP-CA-Y302'].geometry} material={materials.KHAKI1} />
          <mesh geometry={nodes['STOFF-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[130.5, -20, 6.2]} rotation={[-0.05, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['STOFF-CA-Y302001'].geometry} material={materials.LIGHTSTEELBLUE2} position={[130.5, -320, 6.2]} rotation={[-0.05, -Math.PI / 2, 0]} />
        </group>
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201031'].geometry} material={materials.MAROON2} position={[-136.5, 331, -426.2]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201032'].geometry} material={materials.MAROON2} position={[-136.5, 196, -426.2]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201033'].geometry} material={materials.MAROON2} position={[-136.5, 61, -426.2]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201034'].geometry} material={materials.MAROON2} position={[135, 462, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201035'].geometry} material={materials.MAROON2} position={[60, 445, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201036'].geometry} material={materials.MAROON2} position={[5, 445, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201037'].geometry} material={materials.MAROON2} position={[5, 462, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201038'].geometry} material={materials.MAROON2} position={[-81.059, 447.63, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201039'].geometry} material={materials.MAROON2} position={[-137.627, 391.06, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201040'].geometry} material={materials.MAROON2} position={[-152, 350, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201041'].geometry} material={materials.MAROON2} position={[-152, 200, -457.3]} />
        <mesh geometry={nodes['RIVET-T18-C-CA-Y201042'].geometry} material={materials.MAROON2} position={[-152, 20, -457.3]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201'].geometry} material={materials.LIGHTSTEELBLUE2} position={[143, 50, -457.85]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201001'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-147, 50, -457.85]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201002'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-147, 280, -457.85]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201003'].geometry} material={materials.LIGHTSTEELBLUE2} position={[143, 280, -457.85]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201004'].geometry} material={materials.LIGHTSTEELBLUE2} position={[95, 457, -457.85]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201005'].geometry} material={materials.LIGHTSTEELBLUE2} position={[-35, 457, -457.85]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201006'].geometry} material={materials.LIGHTSTEELBLUE2} position={[151.05, 100, -448]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y201007'].geometry} material={materials.LIGHTSTEELBLUE2} position={[151.05, 380, -448]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y302'].geometry} material={materials.GRAY62} position={[-150.9, 65, -429.7]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y302001'].geometry} material={materials.GRAY62} position={[-150.9, 305, -429.7]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes['LOCK-TOP-CA-Y302002'].geometry} material={materials.GRAY62} position={[-25, 460.9, -429.7]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['TOP-RING-CA-Y302'].geometry} material={materials.LIGHTSALMON3} />
        <mesh geometry={nodes['TOP-RING-COVER-CA-Y302'].geometry} material={materials.LIGHTGOLDENROD2} />
        <mesh geometry={nodes['TOP-PANEL-CA-Y302_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh onAfterRender={props.onAfterRender} geometry={nodes['TOP-PANEL-CA-Y302_2'].geometry} material={materials.RED} />
      </group>
    </group>
  )
}

useGLTF.preload('/Y70.glb')
