/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 BackSides.glb 
*/

import React, { useRef } from 'react'
import { PerspectiveCamera, useGLTF } from '@react-three/drei'

export function BackSides(props) {
  const { nodes, materials } = useGLTF('/BackSides.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['REAR-PANEL-CA-Y302'].geometry} material={materials.GRAY62} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/BackSides.glb')
