/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 BottomFaces.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BottomFaces(props) {
  const { nodes, materials } = useGLTF('/BottomFaces.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <group position={[0, -232.501, -17]}>
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201071'].geometry} material={materials['Paint Matte White #1.185']} position={[-40, 0.7, -32]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['BOTTOM-PLASTIC-CA-Y302001'].geometry} material={materials['Paint Matte White #1.238']} />
          <mesh geometry={nodes['BOTTOM-PLASTIC-CA-Y302002'].geometry} material={materials['Paint Matte White #1.239']} />
          <mesh geometry={nodes['BOTTOM-RUBBER-CA-Y302001'].geometry} material={materials['Paint Matte White #1.236']} />
          <mesh geometry={nodes['BOTTOM-RUBBER-CA-Y302002'].geometry} material={materials['Paint Matte White #1.237']} />
          <mesh geometry={nodes['FAN-BRACKET-CA-Y302001'].geometry} material={materials['Paint Matte White #1.219']} />
          <mesh geometry={nodes['SCREW-FAN001'].geometry} material={materials['Paint Matte White #1.214']} position={[-29.5, 248.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN003'].geometry} material={materials['Paint Matte White #1.215']} position={[-29.5, 263.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN005'].geometry} material={materials['Paint Matte White #1.218']} position={[-29.5, 128.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN007'].geometry} material={materials['Paint Matte White #1.220']} position={[-29.5, 143.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN009'].geometry} material={materials['Paint Matte White #1.221']} position={[-134.5, 263.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN011'].geometry} material={materials['Paint Matte White #1.225']} position={[-134.5, 248.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN013'].geometry} material={materials['Paint Matte White #1.226']} position={[-134.5, 128.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN015'].geometry} material={materials['Paint Matte White #1.227']} position={[-29.5, 368.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-FAN017'].geometry} material={materials['Paint Matte White #1.232']} position={[-134.5, 143.5, -1.6]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101009'].geometry} material={materials['Paint Matte White #1.213']} position={[18, 230, 3.5]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101011'].geometry} material={materials['Paint Matte White #1.222']} position={[18, 390, 3.5]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101013'].geometry} material={materials['Paint Matte White #1.235']} position={[18, 70, 3.5]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes['BOTTOM-FILTER-CA-Y302001'].geometry} material={materials['Paint Matte White #1.210']} position={[0, 0, 0.4]} />
          <mesh geometry={nodes['POWER-SUPPORT-CA-Y302001'].geometry} material={materials['Paint Matte White #1.240']} />
          <mesh geometry={nodes['VELCRO-B-CA-Y302001'].geometry} material={materials['Paint Matte White #1.209']} position={[95, 190, -1.2]} />
          <mesh geometry={nodes['VELCRO-B-CA-Y302003'].geometry} material={materials['Paint Matte White #1.211']} position={[95, 100, -1.2]} />
          <mesh geometry={nodes['VELCRO-B-CA-Y302005'].geometry} material={materials['Paint Matte White #1.212']} position={[95, 280, -1.2]} />
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-103.123, 21.6, 415.664]} rotation={[-Math.PI / 2, 0, 2.356]}>
              <group position={[-0.6, 0, -5]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['1206-CA-Y302_AF0001'].geometry} material={materials['Paint Matte White #1.055']} />
                <mesh geometry={nodes['1206-CA-Y302_AF0002'].geometry} material={materials['Paint Matte White #1.056']} />
              </group>
              <group position={[-9, 0, 6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh geometry={nodes['1206-CA-Y302_AF1001'].geometry} material={materials['Paint Matte White #1.057']} />
                <mesh geometry={nodes['1206-CA-Y302_AF1002'].geometry} material={materials['Paint Matte White #1.058']} />
              </group>
              <group position={[9, 0, 6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh geometry={nodes['1206-CA-Y302_AF2001'].geometry} material={materials['Paint Matte White #1.071']} />
                <mesh geometry={nodes['1206-CA-Y302_AF2002'].geometry} material={materials['Paint Matte White #1.072']} />
              </group>
              <group position={[-9, 0, -6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh geometry={nodes['1206-CA-Y302_AF3001'].geometry} material={materials['Paint Matte White #1.063']} />
                <mesh geometry={nodes['1206-CA-Y302_AF3002'].geometry} material={materials['Paint Matte White #1.064']} />
              </group>
              <group position={[9, 0, -6.1]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
                <mesh geometry={nodes['1206-CA-Y302_AF4001'].geometry} material={materials['Paint Matte White #1.069']} />
                <mesh geometry={nodes['1206-CA-Y302_AF4002'].geometry} material={materials['Paint Matte White #1.070']} />
              </group>
              <group position={[22.75, 1.25, 0]} rotation={[0, -1.571, 0]}>
                <mesh geometry={nodes['CON-USB-3-0-NEW_AF2001'].geometry} material={materials['Paint Matte White #1.067']} />
                <mesh geometry={nodes['CON-USB-3-0-NEW_AF2002'].geometry} material={materials['Paint Matte White #1.068']} />
              </group>
              <group position={[-22.75, 1.25, 0]} rotation={[0, -1.571, 0]}>
                <mesh geometry={nodes['CON-USB-3-0-NEW_AF3001'].geometry} material={materials['Paint Matte White #1.042']} />
                <mesh geometry={nodes['CON-USB-3-0-NEW_AF3002'].geometry} material={materials['Paint Matte White #1.043']} />
              </group>
              <group position={[0, 3, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['KS-27H10B050NN-X5_2_1_AF0001'].geometry} material={materials['Paint Matte White #1.059']} />
                <mesh geometry={nodes['KS-27H10B050NN-X5_2_1_AF0002'].geometry} material={materials['Paint Matte White #1.060']} />
                <mesh geometry={nodes['KS-27H10B050NN-X5_2_1_AF0003'].geometry} material={materials['Paint Matte White #1.061']} />
                <mesh geometry={nodes['KS-27H10B050NN-X5_2_1_AF0004'].geometry} material={materials['Paint Matte White #1.062']} />
              </group>
              <group position={[-40, 15, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['TYPC-180_AF5001'].geometry} material={materials['Paint Matte White #1.065']} />
                <mesh geometry={nodes['TYPC-180_AF5002'].geometry} material={materials['Paint Matte White #1.066']} />
              </group>
              <group position={[33, -1.6, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0001'].geometry} material={materials['Paint Matte White #1.044']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0002'].geometry} material={materials['Paint Matte White #1.045']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0003'].geometry} material={materials['Paint Matte White #1.046']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0004'].geometry} material={materials['Paint Matte White #1.047']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0005'].geometry} material={materials['Paint Matte White #1.048']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0006'].geometry} material={materials['Paint Matte White #1.049']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0007'].geometry} material={materials['Paint Matte White #1.050']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0008'].geometry} material={materials['Paint Matte White #1.051']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0009'].geometry} material={materials['Paint Matte White #1.052']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0010'].geometry} material={materials['Paint Matte White #1.053']} />
                <mesh geometry={nodes['WAFER-HOUSING-2-P20-V-10P_AF0011'].geometry} material={materials['Paint Matte White #1.054']} />
              </group>
              <group position={[0, -1.6, 10.9]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0001'].geometry} material={materials['Paint Matte White #1.074']} />
                <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0002'].geometry} material={materials['Paint Matte White #1.075']} />
                <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0003'].geometry} material={materials['Paint Matte White #1.076']} />
                <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0004'].geometry} material={materials['Paint Matte White #1.077']} />
                <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0005'].geometry} material={materials['Paint Matte White #1.078']} />
                <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0006'].geometry} material={materials['Paint Matte White #1.079']} />
                <mesh geometry={nodes['WAFER-HOUSING-P20-V-6P_AF0007'].geometry} material={materials['Paint Matte White #1.080']} />
              </group>
              <mesh geometry={nodes['AUDIO-JACK-PHANTOM410_AF3001'].geometry} material={materials['Paint Matte White #1.041']} position={[40, 0, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
              <mesh geometry={nodes['PCB-CA-Y302_AF0001'].geometry} material={materials['Paint Matte White #1.073']} />
            </group>
            <group position={[-110.76, 21.6, 423.301]} rotation={[Math.PI / 2, 0, Math.PI / 4]}>
              <mesh geometry={nodes.COMBINE6001.geometry} material={materials['Glass Basic White #2.001']} />
              <mesh geometry={nodes['CUT-REVOLVE1001'].geometry} material={materials['Paint Matte White #1.040']} />
            </group>
          </group>
          <mesh geometry={nodes['BOTTOM-PANEL-CA-Y302001'].geometry} material={materials['Paint Matte White #1.035']} />
          <mesh geometry={nodes['BOTTOM-PANEL-V3-CA-Y302001'].geometry} material={materials['Paint Matte White #1.036']} />
          <mesh geometry={nodes['BOTTOM-PANEL-V3-CA-Y302002'].geometry} material={materials['Paint Matte White #1.037']} />
          <mesh geometry={nodes['BOTTOM-RING-CA-Y302001'].geometry} material={materials['Paint Matte White #2.001']} />
          <mesh geometry={nodes['GLASS-SUPPORT-CA-Y302001'].geometry} material={materials['Paint Matte White #1.039']} position={[-153, 314, -28.4]} rotation={[0, 0, Math.PI]} />
          <mesh geometry={nodes['GLASS-SUPPORT-CA-Y302003'].geometry} material={materials['Paint Matte White #1.081']} position={[110, 463, -28.4]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes['GLASS-SUPPORT-CA-Y302005'].geometry} material={materials['Paint Matte White #1.082']} position={[-20, 463, -28.4]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes['GLASS-SUPPORT-V2-CA-Y302001'].geometry} material={materials['Paint Matte White #1.034']} position={[-153, 14, -28.4]} rotation={[0, 0, Math.PI]} />
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['FRONT-GLASS-BRACKET-B-CA-Y302001'].geometry} material={materials['Paint Matte White #1.009']} />
            <mesh geometry={nodes['FRONT-GLASS-BRACKET-B-CA-Y302002'].geometry} material={materials['Paint Matte White #1.010']} />
            <mesh geometry={nodes['FRONT-GLASS-BRACKET-B-CA-Y302003'].geometry} material={materials['Paint Matte White #1.011']} />
          </group>
          <mesh geometry={nodes['PSU-BRACKET-CA-Y302001'].geometry} material={materials['Paint Matte White #1.118']} position={[60, 6.9, -55.5]} />
          <mesh geometry={nodes['bottom-cover-ca-y302-1001'].geometry} material={materials['Paint Matte White #2']} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201003'].geometry} material={materials['Paint Matte White #1.001']} position={[50, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201009'].geometry} material={materials['Paint Matte White #1.005']} position={[65, 6.7, -50.5]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201021'].geometry} material={materials['Paint Matte White #1.083']} position={[40, 455, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201023'].geometry} material={materials['Paint Matte White #1.086']} position={[-50, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201029'].geometry} material={materials['Paint Matte White #1.091']} position={[-72.574, 446.213, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201031'].geometry} material={materials['Paint Matte White #1.092']} position={[-40, 455, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201035'].geometry} material={materials['Paint Matte White #1.138']} position={[124, 307, -0.7]} rotation={[-Math.PI, 0, -1.588]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201037'].geometry} material={materials['Paint Matte White #1.139']} position={[139, 439, -40]} rotation={[-1.451, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201039'].geometry} material={materials['Paint Matte White #1.143']} position={[-145, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201067'].geometry} material={materials['Paint Matte White #1.180']} position={[139, 320, -40]} rotation={[-1.451, -Math.PI / 2, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201077'].geometry} material={materials['Paint Matte White #1.189']} position={[120, 455, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201079'].geometry} material={materials['Paint Matte White #1.190']} position={[-136.213, 382.574, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201085'].geometry} material={materials['Paint Matte White #1.193']} position={[135, 437, -0.7]} rotation={[-Math.PI, 0, -1.588]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201087'].geometry} material={materials['Paint Matte White #1.197']} position={[-140, 0.7, -32]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201091'].geometry} material={materials['Paint Matte White #1.199']} position={[80, 6.7, -50.5]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201095'].geometry} material={materials['Paint Matte White #1.202']} position={[145, 13.5, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201097'].geometry} material={materials['Paint Matte White #1.242']} position={[135, 329, -0.7]} rotation={[-Math.PI, 0, -1.588]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201099'].geometry} material={materials['Paint Matte White #1.243']} position={[-145, 355, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201101'].geometry} material={materials['Paint Matte White #1.255']} position={[-145, 23, -0.7]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['RIVET-T18-C-CA-Y201103'].geometry} material={materials['Paint Matte White #1.256']} position={[40, 0.7, -32]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-4001'].geometry} material={materials['Paint Matte White #1.006']} position={[146.5, 26, -1.9]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-4007'].geometry} material={materials['Paint Matte White #1.182']} position={[146.5, 300, -1.9]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-4009'].geometry} material={materials['Paint Matte White #1.195']} position={[146.5, 437, -1.9]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-4011'].geometry} material={materials['Paint Matte White #1.196']} position={[146.5, 163, -1.9]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-5005'].geometry} material={materials['Paint Matte White #1.134']} position={[59.7, 44, -40]} rotation={[-1.448, -1.571, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-5007'].geometry} material={materials['Paint Matte White #1.194']} position={[120, 301.8, -40]} rotation={[-Math.PI / 2, 0, -0.003]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-7001'].geometry} material={materials['Paint Matte White #1.003']} position={[103.716, 65.385, 2.5]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-7003'].geometry} material={materials['Paint Matte White #1.031']} position={[0, 437, 2.5]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-7005'].geometry} material={materials['Paint Matte White #1.084']} position={[102, 437, 2.5]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-7007'].geometry} material={materials['Paint Matte White #1.089']} position={[0, 18, 2.5]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-7009'].geometry} material={materials['Paint Matte White #1.184']} position={[-103.716, 389.615, 2.5]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes['SCREW-F-UNC6-32-7011'].geometry} material={materials['Paint Matte White #1.186']} position={[-102, 18, 2.5]} rotation={[-Math.PI, 0, 0]} />
          <mesh geometry={nodes.UM_PROD_BODY001.geometry} material={materials['Paint Matte White #1.254']} onAfterRender={props.onAfterRender}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/BottomFaces.glb')
