/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 BottomGears0.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BottomGears0(props) {
  const { nodes, materials } = useGLTF('/BottomGears0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BOTTOM-PLASTIC-CA-Y302'].geometry} material={materials.GRAY62} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['BOTTOM-RUBBER-CA-Y302_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['BOTTOM-RUBBER-CA-Y302_2'].geometry} material={materials.GRAY62} />
      </group>
    </group>
  )
}

useGLTF.preload('/BottomGears0.glb')
