/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 BottomGears1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BottomGears1(props) {
  const { nodes, materials } = useGLTF('/BottomGears1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FAN-BRACKET-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['BOTTOM-FILTER-CA-Y302'].geometry} material={materials.LIGHTSALMON3} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/BottomGears1.glb')
