/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 BottomFans0.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BottomFans0(props) {
  const { nodes, materials } = useGLTF('/BottomFans0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FAN-140X25'].geometry} material={materials.CYAN4} position={[-0.072, 0.015, 0.104]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FAN-140X25001'].geometry} material={materials.CYAN4} position={[-0.072, 0.015, 0.244]} rotation={[Math.PI, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/BottomFans0.glb')
