/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 BottomSides.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BottomSides(props) {
  const { nodes, materials } = useGLTF('/BottomSides.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['bottom-cover-ca-y302-1'].geometry} material={materials.LIGHTSTEELBLUE2} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/BottomSides.glb')
