/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 BottomFans1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BottomFans1(props) {
  const { nodes, materials } = useGLTF('/BottomFans1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FAN-120'].geometry} material={materials.CYAN4} position={[-0.082, 0.015, 0.076]} rotation={[0, 0, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes['FAN-120001'].geometry} material={materials.CYAN4} position={[-0.082, 0.015, 0.196]} rotation={[0, 0, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes['FAN-120002'].geometry} material={materials.CYAN4} position={[-0.082, 0.015, 0.316]} rotation={[0, 0, -Math.PI]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/BottomFans1.glb')
