/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Cpu.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cpu(props) {
  const { nodes, materials } = useGLTF('/Cpu.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.08, 0.264, -0.02]} rotation={[1.579, 0, -Math.PI / 2]} scale={0.001}>
        <mesh geometry={nodes['PA-Y206-MINI-HUB001'].geometry} material={materials['Paint Matte White #1.140']} />
        <mesh geometry={nodes['PA-Y206-MINI-HUB002'].geometry} material={materials['Paint Matte White #1.141']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Cpu.glb')
