/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 FanInners0.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FanInners0(props) {
  const { nodes, materials } = useGLTF('/FanInners0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FAN-120001'].geometry} material={materials['Paint Matte White #1.216']} position={[-0.082, 0.032, -0.037]} rotation={[0, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['FAN-120004'].geometry} material={materials['Paint Matte White #1.228']} position={[-0.082, 0.032, -0.157]} rotation={[0, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['FAN-120007'].geometry} material={materials['Paint Matte White #1.230']} position={[-0.082, 0.032, 0.083]} rotation={[0, 0, Math.PI]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/FanInners0.glb')
