/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 FanInners1.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FanInners1(props) {
  const { nodes, materials } = useGLTF('/FanInners1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FAN-140X25001'].geometry} material={materials['Paint Matte White #1.223']} position={[-0.072, 0.032, 0.011]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FAN-140X25004'].geometry} material={materials['Paint Matte White #1.233']} position={[-0.072, 0.032, -0.129]} rotation={[Math.PI, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/FanInners1.glb')
