/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 FanOuters0.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function FanOuters0(props) {
  const { nodes, materials } = useGLTF('/FanOuters0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FAN-120002'].geometry} material={materials['Paint Matte White #1.217']} position={[-0.082, 0.032, -0.037]} rotation={[0, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['FAN-120005'].geometry} material={materials['Paint Matte White #1.229']} position={[-0.082, 0.032, -0.157]} rotation={[0, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['FAN-120008'].geometry} material={materials['Paint Matte White #1.231']} position={[-0.082, 0.032, 0.083]} rotation={[0, 0, Math.PI]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/FanOuters0.glb')
