/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 GlassSides.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GlassSides(props) {
  const { nodes, materials } = useGLTF('/GlassSides.glb')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['FRONT-GLASS-CA-Y302_1'].geometry} material={materials.LIGHTCYAN} />
        <mesh geometry={nodes['FRONT-GLASS-45-CA-Y302'].geometry} material={materials.LIGHTCYAN} />
        <mesh geometry={nodes['FRONT-GLASS-CA-Y302_2'].geometry} material={materials.GRAY59} />
        <mesh geometry={nodes['LF-GLASS-CA-Y302_1'].geometry} material={materials.LIGHTCYAN} />
        <mesh geometry={nodes['LF-GLASS-CA-Y302_2'].geometry} material={materials.GRAY59} />
      </group>
    </group>
  )
}

useGLTF.preload('/GlassSides.glb')
