/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 GlassFaces.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GlassFaces(props) {
  const { nodes, materials } = useGLTF('/GlassFaces.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FRONT-GLASS-45-CA-Y302001'].geometry} material={materials['Material.002']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FRONT-GLASS-CA-Y302001'].geometry} material={materials['Material.002']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['LF-GLASS-CA-Y302001'].geometry} material={materials['Material.002']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/GlassFaces.glb')
