/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Hyte.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hyte(props) {
  const { nodes, materials } = useGLTF('/Hyte.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.02, 0.192, 0.008]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-BASE-CA-Y101_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-BASE-CA-Y101_2'].geometry} material={materials.GRAY62} />
      </group>
      <group position={[-0.02, 0.192, 0.008]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_2_1'].geometry} material={materials.GRAY64} />
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_2_2'].geometry} material={materials.LIGHTSTEELBLUE2} />
      </group>
    </group>
  )
}

useGLTF.preload('/Hyte.glb')
