/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 InnerFaces0.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function InnerFaces0(props) {
  const { nodes, materials } = useGLTF('/InnerFaces0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['MB-SUPPORT-CA-Y302001'].geometry} material={materials['Paint Matte White #1.027']} position={[0.059, 0.087, -0.214]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/InnerFaces0.glb')
