/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 InnerFaces1.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function InnerFaces1(props) {
  const { nodes, materials } = useGLTF('/InnerFaces1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['GROMMET-NEW-6-30001'].geometry} material={materials['Paint Matte White #1.135']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['MB-SUPPORT-CA-Y302002'].geometry} material={materials['Paint Matte White #1.028']} position={[0.059, 0.087, -0.214]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/InnerFaces1.glb')
