/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 InnerSides.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function InnerSides(props) {
  const { nodes, materials } = useGLTF('/InnerSides.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BOTTOM-PANEL-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-FILTER-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['TOP-COVER-PLASTIC-CA-Y302_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['TOP-COVER-PLASTIC-CA-Y302_2'].geometry} material={materials.LIMEGREEN} />
      </group>
    </group>
  )
}

useGLTF.preload('/InnerSides.glb')
