/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Mechanic5.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mechanic5(props) {
  const { nodes, materials } = useGLTF('/Mechanic5.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.08, 0.247, 0.213]} rotation={[1.579, 0, -Math.PI / 2]} scale={0.001}>
        <mesh geometry={nodes['PA-Y206-MINI-HUB_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['PA-Y206-MINI-HUB_2'].geometry} material={materials.OLIVEDRAB2} />
      </group>
    </group>
  )
}

useGLTF.preload('/Mechanic5.glb')
