/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Mechanic0.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mechanic0(props) {
  const { nodes, materials } = useGLTF('/Mechanic0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3-12CM-WATERCOOLER-30H-DEEPCOOL'].geometry} material={materials.OLIVEDRAB2} position={[0.139, 0.239, 0.384]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/Mechanic0.glb')
