/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Mechanic4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mechanic4(props) {
  const { nodes, materials } = useGLTF('/Mechanic4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['HDD-TRAY-CA-Y302'].geometry} material={materials.LIGHTSTEELBLUE2} position={[0.106, 0.292, 0.006]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['HDD-TRAY-CA-Y302001'].geometry} material={materials.LIGHTSTEELBLUE2} position={[0.075, 0.292, 0.006]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes.SERIAL_ATA_HD_3.geometry} material={materials.DARKSEAGREEN1} position={[0.109, 0.241, 0.02]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes.SERIAL_ATA_HD_3001.geometry} material={materials.DARKSEAGREEN1} position={[0.078, 0.241, 0.02]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-HDD-CA-Y302'].geometry} material={materials.LIGHTGOLDENROD2} position={[0.075, 0.292, 0.01]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/Mechanic4.glb')
