/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Mechanic1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mechanic1(props) {
  const { nodes, materials } = useGLTF('/Mechanic1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['VGA-CARD-ATI'].geometry} material={materials.CADETBLUE1} position={[-0.048, 0.048, 0.008]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/Mechanic1.glb')
