/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Mechanic2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mechanic2(props) {
  const { nodes, materials } = useGLTF('/Mechanic2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['EPE-PCIE-CA-Y302'].geometry} material={materials.LIMEGREEN} position={[-0.041, 0.241, 0.13]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/Mechanic2.glb')
