/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Mechanic3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mechanic3(props) {
  const { nodes, materials } = useGLTF('/Mechanic3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.064, 0.108, 0.077]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes['PSU-D185_1'].geometry} material={materials.WHITESMOKE} />
        <mesh geometry={nodes['PSU-D185_2'].geometry} material={materials.TOMATO2} />
        <mesh geometry={nodes['PSU-D185_3'].geometry} material={materials.GRAY28} />
      </group>
    </group>
  )
}

useGLTF.preload('/Mechanic3.glb')
