/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 MotherBoard.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MotherBoard(props) {
  const { nodes, materials } = useGLTF('/MotherBoard.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.046, 0.063, -0.181]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101001'].geometry} material={materials['Paint Matte White #1.107']} />
        <mesh geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101002'].geometry} material={materials['Paint Matte White #1.108']} />
        <mesh geometry={nodes['JD-PCIE-GPU-PCB-CA-Y101003'].geometry} material={materials['Paint Matte White #1.109']} />
      </group>
      <group position={[-0.02, 0.209, -0.224]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-BASE-CA-Y101001'].geometry} material={materials['Paint Matte White #1.105']} />
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-BASE-CA-Y101002'].geometry} material={materials['Paint Matte White #1.106']} />
      </group>
      <group position={[-0.02, 0.209, -0.224]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_2_0'].geometry} material={materials['Paint Matte White #2.002']} />
        <mesh geometry={nodes['BKT-PCIE-PLASTIC-COVER-CA-Y101_2_1'].geometry} material={materials['Paint Matte White #1.104']} />
      </group>
      <mesh geometry={nodes['PCIE-PLASTIC-SUPPORT-CA-Y302001'].geometry} material={materials['Paint Matte White #1.038']} position={[-0.025, 0.055, -0.14]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/MotherBoard.glb')
