/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 OuterFrames.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OuterFrames(props) {
  const { nodes, materials } = useGLTF('/OuterFrames.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BOTTOM-RING-CA-Y302'].geometry} material={materials.LIGHTSALMON3} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FRONT-GLASS-BRACKET-CA-Y302'].geometry} material={materials.GRAY62} position={[0, 0.434, 0.463]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['LF-GLASS-BRACKET-CA-Y302'].geometry} material={materials.GRAY62} position={[-0.153, 0.435, 0]} scale={0.001} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes['TOP-PANEL-CA-Y302_1'].geometry} material={materials.LIGHTSTEELBLUE2} />
        <mesh geometry={nodes['TOP-PANEL-CA-Y302_2'].geometry} material={materials.RED} />
      </group>
      <mesh geometry={nodes['TOP-RING-CA-Y302'].geometry} material={materials.LIGHTSALMON3} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/OuterFrames.glb')
