/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 PinPoints.glb --keepmaterials 
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function PinPoints(props) {
  const { nodes, materials } = useGLTF('/PinPoints.glb')
  const [selectedIndex, setSelectedIndex] = useState(undefined)
  useEffect(()=>{
      props.onPinPointSelected(selectedIndex)
    }, [selectedIndex])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[-0.08, 0.435, 0.235]} scale={0.005} onClick={()=>{setSelectedIndex(1)}}/>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.001']} position={[-0.022, 0.209, -0.146]} scale={0.005} onClick={()=>{setSelectedIndex(2)}}/>
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.001']} position={[0.055, 0.135, -0.112]} scale={0.005}  onClick={()=>{setSelectedIndex(3)}}/>
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.001']} position={[0.063, 0.293, -0.14]} scale={0.005}  onClick={()=>{setSelectedIndex(4)}}/>
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.001']} position={[-0.04, 0.078, -0.105]} scale={0.005}  onClick={()=>{setSelectedIndex(5)}}/>
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.001']} position={[0.068, 0.256, -0.011]} scale={0.005}  onClick={()=>{setSelectedIndex(6)}}/>
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.001']} position={[-0.088, 0.064, -0.023]} scale={0.005}  onClick={()=>{setSelectedIndex(7)}}/>
    </group>
    
  )
}

useGLTF.preload('/PinPoints.glb')
