/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 PinPoints.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PinPoints(props) {
  const { nodes, materials } = useGLTF('/PinPoints.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.006']} material-color="red" position={[-0.12, 0.227, 0.419]} scale={0.003} onClick={()=>{props.onPinPointSelected(1)}}/>
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.006']} material-color="red" position={[-0.084, 0.108, 0.159]} scale={0.003} onClick={()=>{props.onPinPointSelected(2)}}/>
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.006']} material-color="red" position={[0.077, 0.23, 0.218]} scale={0.003} onClick={()=>{props.onPinPointSelected(3)}}/>
    </group>
  )
}

useGLTF.preload('/PinPoints.glb')



