/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Plugins.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plugins(props) {
  const { nodes, materials } = useGLTF('/Plugins.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['AUDIO-JACK-PHANTOM410_AF3'].geometry} material={materials.LIGHTSTEELBLUE3} position={[-0.131, 0.022, 0.387]} rotation={[-Math.PI, Math.PI / 4, -Math.PI / 2]} scale={0.001} />
      <group position={[-0.111, 0.022, 0.423]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={0.001}>
        <mesh geometry={nodes.COMBINE6_1.geometry} material={materials.LIMEGREEN} />
        <mesh geometry={nodes.COMBINE6_2.geometry} material={materials.LIGHTSTEELBLUE2} />
      </group>
    </group>
  )
}

useGLTF.preload('/Plugins.glb')
