/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 PowerSupply.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PowerSupply(props) {
  const { nodes, materials } = useGLTF('/PowerSupply.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.064, 0.125, -0.156]} rotation={[-Math.PI / 2, -1.571, 0]} scale={0.001}>
        <mesh geometry={nodes['PSU-D185001'].geometry} material={materials['Paint Matte White #1.094']} />
        <mesh geometry={nodes['PSU-D185002'].geometry} material={materials['Paint Matte White #1.095']} />
        <mesh geometry={nodes['PSU-D185003'].geometry} material={materials['Paint Matte White #1.096']} />
        <mesh geometry={nodes['PSU-D185004'].geometry} material={materials['Paint Matte White #1.097']} />
        <mesh geometry={nodes['PSU-D185005'].geometry} material={materials['Paint Matte White #1.098']} />
        <mesh geometry={nodes['PSU-D185006'].geometry} material={materials['Paint Matte White #1.099']} />
        <mesh geometry={nodes['PSU-D185007'].geometry} material={materials['Paint Matte White #1.100']} />
        <mesh geometry={nodes['PSU-D185008'].geometry} material={materials['Paint Matte White #1.101']} />
        <mesh geometry={nodes['PSU-D185009'].geometry} material={materials['Paint Matte White #1.102']} />
      </group>
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201001'].geometry} material={materials['Paint Matte White #1']} position={[0.135, 0.067, -0.226]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/PowerSupply.glb')
