/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 SideFaces.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SideFaces(props) {
  const { nodes, materials } = useGLTF('/SideFaces.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FRONT-GLASS-BRACKET-CA-Y302001'].geometry} material={materials['Paint Matte White #1.246']} position={[0, 0.451, 0.231]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['FRONT-GLASS-CA-Y302002'].geometry} material={materials['Paint Matte White #1.248']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['LF-GLASS-BRACKET-CA-Y302001'].geometry} material={materials['Paint Matte White #1.205']} position={[-0.153, 0.452, -0.233]} scale={0.001} />
      <mesh geometry={nodes['LF-GLASS-CA-Y302002'].geometry} material={materials['Paint Matte White #1.203']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-SUPPORT-CA-Y302001'].geometry} material={materials['Paint Matte White #1.136']} position={[0.14, 0.069, 0.083]} rotation={[Math.PI, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-SUPPORT-CA-Y302002'].geometry} material={materials['Paint Matte White #1.137']} position={[0.14, 0.069, 0.083]} rotation={[Math.PI, -1.571, 0]} scale={0.001} />
      <mesh geometry={nodes['DP-BRACKET-CA-Y307001'].geometry} material={materials['Paint Matte White #1.122']} position={[0.048, 0.084, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-CA-Y201001'].geometry} material={materials['Paint Matte White #1.103']} position={[0.048, 0.084, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-CA-Y201003'].geometry} material={materials['Paint Matte White #1.110']} position={[0.048, 0.125, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-CA-Y201005'].geometry} material={materials['Paint Matte White #1.112']} position={[0.048, 0.104, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-CA-Y201007'].geometry} material={materials['Paint Matte White #1.119']} position={[0.048, 0.186, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-CA-Y201009'].geometry} material={materials['Paint Matte White #1.120']} position={[0.048, 0.165, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-CA-Y201011'].geometry} material={materials['Paint Matte White #1.121']} position={[0.048, 0.206, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-CA-Y201013'].geometry} material={materials['Paint Matte White #1.123']} position={[0.048, 0.145, -0.225]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201001'].geometry} material={materials['Paint Matte White #1.111']} position={[-0.095, 0.067, -0.225]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201003'].geometry} material={materials['Paint Matte White #1.117']} position={[-0.075, 0.067, -0.225]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201005'].geometry} material={materials['Paint Matte White #1.126']} position={[-0.116, 0.067, -0.225]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['BKT-PCIE-V2-CA-Y201007'].geometry} material={materials['Paint Matte White #1.131']} position={[-0.055, 0.067, -0.225]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['REAR-PANEL-CA-Y302001'].geometry} material={materials['Paint Matte White #1.124']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['REAR-PANEL-CA-Y302002'].geometry} material={materials['Paint Matte White #1.125']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-FILTER-CA-Y302003'].geometry} material={materials['Paint Matte White #1.147']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-FILTER-CA-Y302004'].geometry} material={materials['Paint Matte White #1.148']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-CA-Y302001'].geometry} material={materials['Paint Matte White #2.003']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/SideFaces.glb')
