/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 SideFans.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SideFans(props) {
  const { nodes, materials } = useGLTF('/SideFans.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FAN-120004'].geometry} material={materials.CYAN4} position={[0.096, 0.119, 0.383]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['FAN-120005'].geometry} material={materials.CYAN4} position={[0.096, 0.239, 0.383]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['FAN-120006'].geometry} material={materials.CYAN4} position={[0.096, 0.359, 0.383]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/SideFans.glb')
