/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 SoundCard.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SoundCard(props) {
  const { nodes, materials } = useGLTF('/SoundCard.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.075, 0.309, -0.227]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes['HDD-TRAY-CA-Y302001'].geometry} material={materials['Paint Matte White #1.114']} />
        <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101001'].geometry} material={materials['Paint Matte White #1.113']} position={[-59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101003'].geometry} material={materials['Paint Matte White #1.115']} position={[59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.SERIAL_ATA_HD_3001.geometry} material={materials['Paint Matte White #1.116']} position={[50.8, 14.25, -3]} rotation={[0, 0, Math.PI]} />
      </group>
      <group position={[0.106, 0.309, -0.227]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.001}>
        <mesh geometry={nodes['HDD-TRAY-CA-Y302003'].geometry} material={materials['Paint Matte White #1.128']} />
        <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101005'].geometry} material={materials['Paint Matte White #1.127']} position={[-59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['SCREW-HDD-TRAY-CA-Y101007'].geometry} material={materials['Paint Matte White #1.129']} position={[59.5, -2.9, -14]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.SERIAL_ATA_HD_3003.geometry} material={materials['Paint Matte White #1.130']} position={[50.8, 14.25, -3]} rotation={[0, 0, Math.PI]} />
      </group>
      <mesh geometry={nodes['BKT-HDD-CA-Y302001'].geometry} material={materials['Paint Matte White #1.132']} position={[0.075, 0.309, -0.222]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201015'].geometry} material={materials['Paint Matte White #1.030']} position={[0.065, 0.307, -0.226]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201017'].geometry} material={materials['Paint Matte White #1.032']} position={[0.08, 0.368, -0.223]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201025'].geometry} material={materials['Paint Matte White #1.088']} position={[0.08, 0.25, -0.223]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201033'].geometry} material={materials['Paint Matte White #1.133']} position={[0.105, 0.368, -0.223]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201041'].geometry} material={materials['Paint Matte White #1.150']} position={[0.13, 0.368, -0.223]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201083'].geometry} material={materials['Paint Matte White #1.192']} position={[0.13, 0.25, -0.223]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201093'].geometry} material={materials['Paint Matte White #1.200']} position={[0.105, 0.25, -0.223]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/SoundCard.glb')
