/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 TopFaces.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TopFaces(props) {
  const { nodes, materials } = useGLTF('/TopFaces.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.451, 0.231]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001}>
        <mesh geometry={nodes['STANDOFF-SO-2-CA-Y302005'].geometry} material={materials['Paint Matte White #1.247']} position={[-0.6, -30, 4.5]} rotation={[0, -1.571, 0]} />
      </group>
      <group position={[-0.153, 0.452, -0.233]} scale={0.001}>
        <mesh geometry={nodes['STANDOFF-SO-2-CA-Y302001'].geometry} material={materials['Paint Matte White #1.204']} position={[-0.7, -5.2, 60]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes['STANDOFF-SO-2-CA-Y302003'].geometry} material={materials['Paint Matte White #1.208']} position={[-0.7, -5.2, 300]} rotation={[0, -1.571, 0]} />
        <mesh geometry={nodes['TU-RG-PANEL-CA-Y302001'].geometry} material={materials['Paint Matte White #1.206']} position={[-0.7, -5.2, 313]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['TU-RG-PANEL-CA-Y302003'].geometry} material={materials['Paint Matte White #1.207']} position={[-0.7, -5.2, 73]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
      <group position={[0.001, 0.474, -0.225]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.001}>
        <mesh geometry={nodes['FAN-BRACKET-TOP-CA-Y302001'].geometry} material={materials['Paint Matte White #1.171']} />
        <mesh geometry={nodes['STOFF-CA-Y302001'].geometry} material={materials['Paint Matte White #1.172']} position={[130.5, -20, 6.2]} rotation={[-0.05, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['STOFF-CA-Y302003'].geometry} material={materials['Paint Matte White #1.173']} position={[130.5, -320, 6.2]} rotation={[-0.05, -Math.PI / 2, 0]} />
      </group>
      <mesh geometry={nodes['FRONT-GLASS-BRACKET-45-CA-Y302001'].geometry} material={materials['Paint Matte White #1.013']} position={[0, 0.017, -0.233]} scale={0.001} />
      <mesh geometry={nodes['FRONT-GLASS-BRACKET-45-CA-Y302002'].geometry} material={materials['Paint Matte White #1.014']} position={[0, 0.017, -0.233]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-FILTER-CA-Y302001'].geometry} material={materials['Paint Matte White #1.145']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RG-PANEL-FILTER-CA-Y302002'].geometry} material={materials['Paint Matte White #1.146']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['TOP-COVER-CA-Y302001'].geometry} material={materials['Paint Matte White #2.005']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['TOP-COVER-PLASTIC-CA-Y302001'].geometry} material={materials['Paint Matte White #1.244']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['TOP-COVER-PLASTIC-CA-Y302002'].geometry} material={materials['Paint Matte White #1.245']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['TOP-PANEL-CA-Y302001'].geometry} material={materials['Paint Matte White #1.161']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['TOP-PANEL-CA-Y302002'].geometry} material={materials['Paint Matte White #1.162']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['TOP-RING-CA-Y302001'].geometry} material={materials['Paint Matte White #2.004']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['TOP-RING-COVER-CA-Y302001'].geometry} material={materials['Paint Matte White #1.170']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['SCREW-F-UNC6-32-4003'].geometry} material={materials['Paint Matte White #1.012']} position={[-0.076, 0.441, 0.203]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['SCREW-F-UNC6-32-4005'].geometry} material={materials['Paint Matte White #1.026']} position={[-0.126, 0.441, 0.154]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['STANDOFF-SO-CA-Y101001'].geometry} material={materials['Paint Matte White #1.144']} position={[0.152, 0.465, -0.133]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['STANDOFF-SO-CA-Y101003'].geometry} material={materials['Paint Matte White #1.149']} position={[0.152, 0.465, 0.147]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201001'].geometry} material={materials['Paint Matte White #1.155']} position={[-0.147, 0.475, -0.183]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201003'].geometry} material={materials['Paint Matte White #1.156']} position={[-0.035, 0.475, 0.224]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201005'].geometry} material={materials['Paint Matte White #1.157']} position={[0.151, 0.465, -0.133]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201007'].geometry} material={materials['Paint Matte White #1.163']} position={[0.143, 0.475, -0.183]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201009'].geometry} material={materials['Paint Matte White #1.164']} position={[-0.147, 0.475, 0.047]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201011'].geometry} material={materials['Paint Matte White #1.169']} position={[0.095, 0.475, 0.224]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201013'].geometry} material={materials['Paint Matte White #1.174']} position={[0.151, 0.465, 0.147]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y201015'].geometry} material={materials['Paint Matte White #1.176']} position={[0.143, 0.475, 0.047]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y302001'].geometry} material={materials['Paint Matte White #1.158']} position={[-0.025, 0.447, 0.228]} rotation={[Math.PI, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y302003'].geometry} material={materials['Paint Matte White #1.175']} position={[-0.151, 0.447, -0.168]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['LOCK-TOP-CA-Y302005'].geometry} material={materials['Paint Matte White #1.177']} position={[-0.151, 0.447, 0.072]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201043'].geometry} material={materials['Paint Matte White #1.151']} position={[-0.137, 0.443, 0.098]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201045'].geometry} material={materials['Paint Matte White #1.152']} position={[-0.152, 0.474, -0.213]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201047'].geometry} material={materials['Paint Matte White #1.153']} position={[-0.152, 0.474, -0.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201049'].geometry} material={materials['Paint Matte White #1.154']} position={[-0.081, 0.474, 0.215]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201051'].geometry} material={materials['Paint Matte White #1.159']} position={[-0.137, 0.443, -0.172]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201053'].geometry} material={materials['Paint Matte White #1.160']} position={[0.005, 0.474, 0.212]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201055'].geometry} material={materials['Paint Matte White #1.165']} position={[0.005, 0.474, 0.229]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201057'].geometry} material={materials['Paint Matte White #1.166']} position={[0.06, 0.474, 0.212]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201059'].geometry} material={materials['Paint Matte White #1.167']} position={[-0.137, 0.443, -0.037]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201061'].geometry} material={materials['Paint Matte White #1.168']} position={[-0.152, 0.474, 0.117]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201063'].geometry} material={materials['Paint Matte White #1.178']} position={[0.135, 0.474, 0.229]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201065'].geometry} material={materials['Paint Matte White #1.179']} position={[-0.138, 0.474, 0.159]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201007'].geometry} material={materials['Paint Matte White #1.004']} position={[0.134, 0.474, 0.194]} rotation={[Math.PI / 2, 0, -1.516]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201011'].geometry} material={materials['Paint Matte White #1.007']} position={[0.064, 0.474, -0.183]} rotation={[Math.PI / 2, 0, -1.516]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201013'].geometry} material={materials['Paint Matte White #1.008']} position={[-0.139, 0.455, -0.232]} rotation={[0, 0, -1.408]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201019'].geometry} material={materials['Paint Matte White #1.033']} position={[0.055, 0.466, -0.232]} rotation={[0, 0, -1.408]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201027'].geometry} material={materials['Paint Matte White #1.090']} position={[0.139, 0.466, -0.232]} rotation={[0, 0, -1.408]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201069'].geometry} material={materials['Paint Matte White #1.183']} position={[-0.055, 0.466, -0.232]} rotation={[0, 0, -1.408]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201075'].geometry} material={materials['Paint Matte White #1.188']} position={[-0.139, 0.466, -0.232]} rotation={[0, 0, -1.408]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201081'].geometry} material={materials['Paint Matte White #1.191']} position={[0.134, 0.474, 0.092]} rotation={[Math.PI / 2, 0, -1.516]} scale={0.001} />
      <mesh geometry={nodes['RIVET-T18-C-CA-Y201089'].geometry} material={materials['Paint Matte White #1.198']} position={[0.064, 0.474, -0.033]} rotation={[Math.PI / 2, 0, -1.516]} scale={0.001} />
      <mesh geometry={nodes['SCREW-F-UNC6-32-5003'].geometry} material={materials['Paint Matte White #1.085']} position={[0.14, 0.464, 0.22]} rotation={[0.123, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['SCREW-F-UNC6-32-5009'].geometry} material={materials['Paint Matte White #1.201']} position={[0.14, 0.452, 0.22]} rotation={[0.123, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['THUMBS-SCREW-6-32001'].geometry} material={materials['Paint Matte White #1.087']} position={[0.069, 0.466, -0.138]} rotation={[-1.797, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['THUMBS-SCREW-6-32003'].geometry} material={materials['Paint Matte White #1.093']} position={[0.069, 0.447, -0.138]} rotation={[-1.797, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['THUMBS-SCREW-6-32005'].geometry} material={materials['Paint Matte White #1.142']} position={[0.069, 0.447, -0.003]} rotation={[-1.797, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes['THUMBS-SCREW-6-32007'].geometry} material={materials['Paint Matte White #1.181']} position={[0.069, 0.466, -0.003]} rotation={[-1.797, -Math.PI / 2, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/TopFaces.glb')
