/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 VideoFrames.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VideoFrames(props) {
  const { nodes, materials } = useGLTF('/VideoFrames.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['FRONT-LCD-CVOER-B-CA-Y307'].geometry} material={materials.LIGHTCYAN} scale={0.001} />
      <group scale={0.001}>
        <mesh geometry={nodes['FRONT-GLASS-BRACKET-45-CA-Y302_1'].geometry} material={materials.RED} />
        <mesh geometry={nodes['FRONT-GLASS-BRACKET-45-CA-Y302_2'].geometry} material={materials.LIGHTCYAN} />
      </group>
      <mesh geometry={nodes['FRONT-GLASS-BRACKET-B-CA-Y302'].geometry} material={materials.LIGHTCYAN} scale={0.001} />
      <mesh geometry={nodes['FRONT-LCD-CVOER-CA-Y307'].geometry} material={materials.LIGHTCYAN} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/VideoFrames.glb')
