/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 VideoProject.glb 
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function VideoProject(props) {
  const { nodes, materials } = useGLTF('/VideoProject.glb')
  const [color, setColor] = useState("pink")
  console.log("!!!color", nodes['TP-GLASS-CA-Y307'].geometry)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['TP-GLASS-CA-Y307'].geometry} material={materials.GRAY90} material-color={color} position={[-0.111, 0.235, 0.421]} rotation={[0, Math.PI / 4, Math.PI / 2]} scale={0.001}  onClick={()=>{setColor("green")}}/>
    </group>
  )
}

useGLTF.preload('/VideoProject.glb')
