/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 VideoGears.glb --keepmaterials 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VideoGears(props) {
  const { nodes, materials } = useGLTF('/VideoGears.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.1, 0.344, 0.178]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.001}>
        <mesh geometry={nodes['LH-W25B-AV1001'].geometry} material={materials['Paint Matte White #1.021']} />
        <mesh geometry={nodes['MINI-DP-7-6001'].geometry} material={materials['Paint Matte White #1.020']} position={[13.05, 24.4, -1.35]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes['TYPE-C-CABLE-180001'].geometry} material={materials['Paint Matte White #1.022']} position={[-17.85, 25.25, -1.755]} rotation={[Math.PI / 2, 0, Math.PI]} />
      </group>
      <group position={[-0.11, 0.252, 0.187]} rotation={[-Math.PI, Math.PI / 4, -Math.PI / 2]} scale={0.001}>
        <mesh geometry={nodes['NV140DQM-N51001'].geometry} material={materials['Paint Matte White #1.015']} />
        <mesh geometry={nodes['TP-GLASS-CA-Y307001'].geometry} material={materials['Paint Matte White #1.016']} position={[0, 0, -1]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes['FRONT-LCD-CVOER-B-CA-Y307001'].geometry} material={materials['Paint Matte White #1.024']} position={[0, 0.017, -0.233]} scale={0.001} />
      <mesh geometry={nodes['FRONT-LCD-CVOER-CA-Y307001'].geometry} material={materials['Paint Matte White #1.249']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FRONT-LCD-CVOER-CA-Y307002'].geometry} material={materials['Paint Matte White #1.250']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FRONT-LCD-CVOER-CA-Y307003'].geometry} material={materials['Paint Matte White #1.251']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FRONT-LCD-CVOER-CA-Y307004'].geometry} material={materials['Paint Matte White #1.252']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['FRONT-LCD-CVOER-CA-Y307005'].geometry} material={materials['Paint Matte White #1.253']} position={[0, 0.017, -0.233]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['LCD-EMI-CVOER-A-CA-Y307001'].geometry} material={materials['Paint Matte White #1.019']} position={[-0.106, 0.375, 0.184]} rotation={[0, -Math.PI / 4, -Math.PI]} scale={0.001} />
      <mesh geometry={nodes['SCREW-M3_L5001'].geometry} material={materials['Paint Matte White #1.017']} position={[-0.13, 0.317, 0.148]} rotation={[0, -Math.PI / 4, 2.649]} scale={0.001} />
      <mesh geometry={nodes['SCREW-M3_L5003'].geometry} material={materials['Paint Matte White #1.018']} position={[-0.071, 0.317, 0.208]} rotation={[0, -Math.PI / 4, 2.649]} scale={0.001} />
      <mesh geometry={nodes['SCREW-M3_L5005'].geometry} material={materials['Paint Matte White #1.023']} position={[-0.071, 0.366, 0.208]} rotation={[0, -Math.PI / 4, 2.649]} scale={0.001} />
      <mesh geometry={nodes['SCREW-M3_L5007'].geometry} material={materials['Paint Matte White #1.025']} position={[-0.13, 0.366, 0.148]} rotation={[0, -Math.PI / 4, 2.649]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/VideoGears.glb')
